### ISSUE TITLE
Works on VS 2015, not on VS 2012 (C2864)

### ISSUE THREAD

**Issue by joshinils** [OneLoneCoder/olcPixelGameEngine#1]
I’m sure this is a problem with my compiler on VS 2012.
I get a lot of C2864, https://msdn.microsoft.com/en-gb/library/acxkb76w.aspx .

How can i make VS 2012 behave?
What other options do i have beside using a newer version with another (newer) compiler?

**Comment by joshinils** [comment]
[here](https://github.com/joshinils/olcPixelGameEngine/blob/master/errorMessages.txt) you go, sorry that it's in German. I can't find an English language pack anymore. i should really switch to a free and newer version anyway.

**Comment by OneLoneCoder** [comment]
Hi Josh, it does seem like its just an old compiler that's the problem. VS17 is free to download, and VS15 should be ok too.

**Comment by joshinils** [comment]
yes, VS 2017 community is free, easy to get and works, I'll start using that from now on
