### ISSUE TITLE
corss product implementation is wrong

### ISSUE THREAD

**Issue by joshinils** [OneLoneCoder/olcPixelGameEngine#100]
https://github.com/OneLoneCoder/olcPixelGameEngine/blob/d39085834833c0bcb7ba476d1e8cf6913524b4b0/olcPixelGameEngine.h#L337 That does not make any sense to me.
First of all, the cross product is only defined for vectors of length 3.
Second, it returns a vector of the same length.
That result should be perpendicular to both of the two input vectors, which is not be possible in 2D.
Since I don't understand the current implementation; what does it do?

**Comment by OneLoneCoder** [comment]
It returns the magnitude of a virtual "z" component. Useful for determining winding orders and such, even in 2D. A nicer description: https://stackoverflow.com/questions/243945/calculating-a-2d-vectors-cross-product

**Comment by joshinils** [comment]
Alright, I would not have suspected something like that, seems I have never come across a need for it and thus have never seen it (or I have but not understood it at the time, which is more likely).
