### ISSUE TITLE
Sound / Music support

### ISSUE THREAD

**Issue by gurkanctn** [OneLoneCoder/olcPixelGameEngine#11]
Important: This is not an issue regarding the current scope of PGE, rather an improvement.

I'm basically trying to play a background music over my PGE based game. And I have not been able to do that.

So, PlayBackgroundMusic(), and PlaySound() functions could be added to the game engine.
 Sounds can be sound FX, similar to Sprites (loaded at the start of the game.)

(PS: I've searched Google, the Discord server and Github for sound related CPP examples, and couldn't find a proper way to do it. WinMM.lib doesn't work in my case (don't know why!))

**Comment by OneLoneCoder** [comment]
HI gurkanctn, Ive recently uploaded (windows only for now) a sound extension for the PGE. There is also a demonstration file showing how to use it. Let me know if you have any problems!

**Comment by gurkanctn** [comment]
Today, I tried to run the sound demo.

I received several (similar) errors about `olc::ResourcePack` that it is not defined.

example line (that gives the error):
`unsigned int SOUND::LoadAudioSample(std::string sWavFile, olc::ResourcePack *pack)`

**Comment by OneLoneCoder** [comment]
Oops, ahem, my apologies, I need to upload the latest pixel game engine header which defines it. Im away from my PC right now, but I'll do it as soon as I can. If you want to just get things going, you could just remove the references to resource pack and any code that uses it (which is only in the Load function - but I'll get the update uploaded asap. Thanks for letting me know!

**Comment by gurkanctn** [comment]
just tried the new version (1.12) and it works :)

Now I can happily add some sound FX to my Altay Tank Game :)
