### ISSUE TITLE
CI/CD, code formatting for olcPGE?

### ISSUE THREAD

**Issue by PerMalmberg** [OneLoneCoder/olcPixelGameEngine#111]
Hello @OneLoneCoder,

First, let me commend you for the great work you've done on PGE. Impressive to say the least. Likewise, your videos are very informative.

Now, to the questions. Do you run CI/CD on the code base? I'm asking because I might have some improvements to the engine code base, but as I don't have access to all the platforms it targets, I can't ensure that I don't break things. Likewise, do you have a test suite that's not part of the official code base? If not, are either thing something you plan to set up?

Secondly, do you have a coding guideline and formatting rules to follow when submitting pull requests? I've found this to be beneficial when accepting PRs in my own project.

Br,

Per

**Comment by OneLoneCoder** [comment]
Hi Per, and thanks!

I run a very simple policy. I don't accept PRs. I'm open to people demonstrating fixes, new features etc. If they end up being used, the contributor gets a credit.

Jx9

**Comment by PerMalmberg** [comment]
Oh, ok. Why not, if you don't mind me asking?

How do you want improvements to be presented?

The [licensing wiki page](https://github.com/OneLoneCoder/olcPixelGameEngine/wiki/Licencing) adds additional terms compared to the [LICENSE.md](https://github.com/OneLoneCoder/olcPixelGameEngine/blob/master/LICENCE.md) file which is prominently displayed on the projects landing page. May I suggest to update the latter and simply link to it from the Wiki?

**Comment by OneLoneCoder** [comment]
Firstly, I prefer to monitor changes very carefully, as I have to take responsibility for when it all goes wrong. Trust me, you don't want hundreds of people contacting you for support only to find the person who made that contribution is suddenly unavailable. 

Secondly, I like to ensure that the contributions/changes align with what my intentions are for the YT channel. If there is a great feature that is lacking, then developing it through videos is great for me as a content maker, and great for the audience who get to see how new features can be derived, constructed, tested and used.

That being said, it's rare that I don't allow people to contribute, but I would suggest discussing it on the discord server where we have testing groups, known contributors, and a great deal more fluidity than via github.

As for the licence, I did a text comparison between the two sources, and other than the year 2019 being enveloped, I could not see any differences between the two.

**Comment by OneLoneCoder** [comment]
And I will add one more thing. Most people want to contribute the same things, spotting patterns in those contributions is far more useful than just accepting PRs. As a result, genuinely useful changes and developments are added to the PGE, in a way that maintains its compatibility, and isn't just because somebody wants a specific implementation. (Not saying that's the case here, but it does happen)

**Comment by PerMalmberg** [comment]
Fair enough.

As to the license - you're right. I read it more carefully now and the two pages say the same thing. It was the preface on the wiki that I thought said things not included in the license itself.
