### ISSUE TITLE
Access Violation error for olc sound pgex extension

### ISSUE THREAD

**Issue by bharatr1993** [OneLoneCoder/olcPixelGameEngine#115]
I am using olc sound pgex extension with olc pixel game engine and I am getting access violation error on InitialiseAudio() and it shows a random address. I am running sound test sample program on visual studio. Have installed windows development platform. Any help is much appreciated!

**Comment by OneLoneCoder** [comment]
Some people seem to have different results depending on if they are compiling 32 or 64 bit. It's a bug.

**Comment by bharatr1993** [comment]
Thank you so much for your reply. I was compiling it for 32 bits. Found
some stuff on the net for replacing DWORD with DWORD_PTR but that didn't
work either. Will try to change to x64.

Regards,
Bharat

**Comment by bharatr1993** [comment]
Thank you so much for your help. Running it x64 solved the initial error. However I got a new error. I did place the audio file in the project folder
![Optimized-20200510_001559-min](https://user-images.githubusercontent.com/63397753/81482645-30b17380-9256-11ea-95be-485a585bc824.jpg)

**Comment by bharatr1993** [comment]
It was my mistake, I put the full path instead of the relative path and it worked.
