### ISSUE TITLE
Blank line of pixels after Clear()

### ISSUE THREAD

**Issue by Jack3G** [OneLoneCoder/olcPixelGameEngine#116]
This is my first time using this. When I clear the screen, there is a blank line of pixels at the very top of the window. 
![Blank Line of Pixels](https://user-images.githubusercontent.com/40290244/81520165-debc3b00-9386-11ea-8cc9-465f234f1439.png)

this is all that I have in OnUserUpdate

```
Clear(olc::GREEN);

return true;
```

**Comment by OneLoneCoder** [comment]
Its hard to say from that screenshot, but I think that could just be the windows titlebar. A way to check would be to use a really low resolution, and perhaps some different coloured pixels to see if it's still there.

**Comment by Jack3G** [comment]
Yeah, I tried what you said and it was still there, until I changed the resolution. It was just the 512 x 480 that I was using :/ Thanks anyway
