### ISSUE TITLE
Leaving fullscreen broken in OS X

### ISSUE THREAD

**Issue by filipre** [OneLoneCoder/olcPixelGameEngine#117]
Hi, 

I'm currently going through the code of the new "Dungeon Warping" tutorial and I noticed that once you enter the full-screen mode, you cannot leave it easily, even if you use `return !GetKey(olc::Key::ESCAPE).bPressed;` as it has been done in the code. Here is a very basic application:

```cpp
#define OLC_PGE_APPLICATION
#include "olcPixelGameEngine.h"

class olcDungeon : public olc::PixelGameEngine
{
public:
    olcDungeon()
    {
        sAppName = "Dungeon Explorer";
    }

public:
    bool OnUserCreate() override
    {
        return true;
    }

    bool OnUserUpdate(float fElapsedTime) override
    {
        return !GetKey(olc::Key::ESCAPE).bPressed;
    }
};

int main()
{
    olcDungeon demo;
    if (demo.Construct(640, 480, 1, 1, true))
        demo.Start();
    return 0;
}
```

I would have expected that pressing `ESC` will close the full-screen window but it did not. In addition, pressing `CMD⌘ + Q` and the whole "spaces" UI do not work either. Not super important but just something to be aware of since the engine has OS X support now.

Best
René

**Comment by OneLoneCoder** [comment]
Interesting. I will pass this on to the supporter of the mac port. Thanks for the information!

**Comment by filipre** [comment]
Small follow up: The problem is with the `OnUserUpdate` function in general and not related to the full screen mode or the `ESC` key. It really does not matter if I return `true` or `false` because in both cases the program continues to run *for me*.

**Comment by MumflrFumperdink** [comment]
Hey, sorry I did not respond sooner! Thanks for telling me about this. It turns out that I did not implement the handling of the OnUserUpdate returns correctly (and, after my own testing, it turned out that the returns of OnUserDestroy were not working as well). So, I attempted a fix of both of those. Can you test out the newer version of https://github.com/MumflrFumperdink/olcPGEMac to make sure it fixes the problem?

**Comment by filipre** [comment]
Great job! That fixed the issue with the `OnUserUpdate`. Thanks!

The fullscreen mode is still a bit broken though since it blocks every other UI-related task. For example, following program basically requires a hard reset.

```cpp
#define OLC_PGE_APPLICATION
#include "olcPixelGameEngine.h"

class olcDungeon : public olc::PixelGameEngine
{
public:
    olcDungeon()
    {
        sAppName = "Dungeon Explorer";
    }

public:
    bool OnUserCreate() override
    {
        return true;
    }

    bool OnUserUpdate(float fElapsedTime) override
    {
        return true; // notice that it is true now
    }
};

int main()
{
    olcDungeon demo;
    if (demo.Construct(640, 480, 1, 1, true))
        demo.Start();
    return 0;
}
```

Many fullscreen applications open in another OS X Space or they allow you to render something "above" them (including the Dock) and they also allow you to quit the app by pressing `CMD⌘ + Q`. Fixing this might be a bit more complicated but I feel like it will prevent a lot of frustration.

Also notice that `return !GetKey(olc::Key::ESCAPE).bPressed;` depends on your frame rate, so when you run into an infinite loop during development and you are in fullscreen, you also have to restart your computer.

Do you think this is a proper issue?
