### ISSUE TITLE
Keyboard handling in multithreaded applications

### ISSUE THREAD

**Issue by gurkanctn** [OneLoneCoder/olcPixelGameEngine#118]
Hello,

I don't know if this is the correct place to ask for help, or whether this is an intended use-case for PGE :)

I've recently adapted the 8-bits of Image Processing video to run with two threads. 
1) capturing video
2) doing image processing algorithms (and keyboard handling)

I've noticed that keyboard states bPressed and bReleased do not work correctly any more. I have to be lucky to switch between algorithms (with keys 1-8).

My issue is: **What is a good practice to read keyboards when we have concurrent threads running?** 

Here's the code if needed:
https://github.com/gurkanctn/Cpp-Projects/blob/master/VideoProcessing_threads.cpp
and the repository: https://github.com/gurkanctn/Cpp-Projects

**Comment by OneLoneCoder** [comment]
Hi Gurkan!

I think the issue here is you sometimes return true from OnUserUpdate(). This is fine, but you only process events after you have returned true, so those single frame events will be missed.

**Comment by gurkanctn** [comment]
Oh, yes. That's certainly true. :) Thanks.

I'll re-organize the code to check for keypress events before returning true.
