### ISSUE TITLE
Have problems Compiling need help 

### ISSUE THREAD

**Issue by mmicha123** [OneLoneCoder/olcPixelGameEngine#119]
expression must have class type at the _n.

https://github.com/OneLoneCoder/olcPixelGameEngine/blob/deaadfef4aea9a08b7d217613666c6744d1184f5/Videos/OneLoneCoder_PGE_Mandelbrot.cpp#L291

**Comment by apidya** [comment]
Try modifying to
pFractal[y_offset + x + 0] = int(_n[3]);
and so on...
