### ISSUE TITLE
Poor FPS when compiling with mingw

### ISSUE THREAD

**Issue by apidya** [OneLoneCoder/olcPixelGameEngine#120]
When compiling the Mandelbrot demo with mingw version 10.1.0 in Code::Blocks 20.03, I achieve a framerate of about 9 to 10 fps. For comparison, javidx9's provided binary runs at 36 to 40 fps on the same system. I made sure I was compiling for release and also tried different optimizations, like -O3 or -march=native to no avail.

**Comment by OneLoneCoder** [comment]
Interesting observation - but not really an "issue" so Im going to close it. I would suggest moving to msys2 if you want an up to date non-windows windows compiler.
