### ISSUE TITLE
Assigning a unique_ptr inside OnUserCreate sometimes hangs application.

### ISSUE THREAD

**Issue by Edward-Billington** [OneLoneCoder/olcPixelGameEngine#122]
Example code that hangs:
```
#define OLC_PGE_APPLICATION
#include "olcPixelGameEngine.h"

class ExampleClass: public olc::PixelGameEngine {
private:
    int pos_x, pos_y;
public:
    ExampleClass() {
        this->pos_x = 0;
        this->pos_y = 0;
    }
};

class Example: public olc::PixelGameEngine
{
public:
    Example()
    {
        sAppName = "Example";
    }

public:
    std::unique_ptr<ExampleClass> testing;

    bool OnUserCreate() override
    {
        testing = std::make_unique<ExampleClass>();
        return true;
    }

    bool OnUserUpdate(float fElapsedTime) override
    {
        return true;
    }
};


int main()
{
    Example demo;
    if (demo.Construct(1024, 1024, 1, 1))
        demo.Start();

    return 0;
}
```

However, if we instead use a different class for "testing", such as an olc::Sprite we don't get this behaviour.
Example that works with no application hang:
```
public:
std::unique_ptr<olc::Sprite> testing;

    bool OnUserCreate() override
    {
        testing = std::make_unique<olc::Sprite>(R"(.\Sprites\test.png)");
        return true;
    }
```

Any ideas of what could be causing this?

###### P.S - There's a high chance that this is "2am Coding Syndrome" and is probably me being a total sausage and missing something very obvious. Apologies if that's the case!

**Comment by matt-hayward** [comment]
There should only ever be one instance of `olc::PixelGameEngine` in your application.

Removing the inheritance from `ExampleClass` should resolve this issue.

**Comment by Edward-Billington** [comment]
> There should only ever be one instance of `olc::PixelGameEngine` in your application.
> 
> Removing the inheritance from `ExampleClass` should resolve this issue.

Thank you!
