### ISSUE TITLE
PGE doesn't register mouse button release out of window

### ISSUE THREAD

**Issue by Philbo01** [OneLoneCoder/olcPixelGameEngine#124]
If a mouse button is pressed while the mouse is over a window, the mouse is then moved off the window and the button is released, when the mouse is moved over the window again GetMouse(n).bHeld continues to register as 'True' even though the mouse button has been released. 

Pressing the mouse button while the mouse is off the window and then releasing it when the mouse is over the window does not reset GetMouse(n).bHeld to 'False'.

Pressing and releasing the button while the mouse is over the window is required to reset GetMouse(n).bHeld to 'False' again.

Regards,
Phil Harvey

PS. I have just started using the Pixel Game Engine and watching the tutorials on Youtube and I am thoughly inpressed. It is so straight forward to use and for someone who hasn't programmed in C++ for a VERY long while (when did "::" become a thing?) it gets out of the way and helps me concentrate on the task at hand. Plus the videos are awesome :)

**Comment by OneLoneCoder** [comment]
This is a tricky one, primarily due to windows. If you click outside of the PGE and then enter the window, the PGE never received the click event. I guess this behavior could be assessed upon detection of moving back into the window - we'll see.
