### ISSUE TITLE
Error while compiling code

### ISSUE THREAD

**Issue by JuiceeGreen** [OneLoneCoder/olcPixelGameEngine#125]
I have had problems with compiling the code when I include olcPixelGameEngine.h. The problem I am facing is : `error LNK2019: unresolved external symbol "public: __thiscall olc::Pixel::Pixel(unsigned char,unsigned char,unsigned char,unsigned char)" (??0Pixel@olc@@QAE@EEEE@Z) referenced in function "void __cdecl olc::`dynamic initializer for 'BLACK''(void)" (??__EBLACK@olc@@YAXXZ)`. I have not used any functionality of the header, I just included it. I am unable to fix this issue.

**Comment by OneLoneCoder** [comment]
As suggested in all the documentation, the videos, the header itself and all the example files, did you ```#define OLC_PGE_APPLICATION``` before including the header file?

**Comment by JuiceeGreen** [comment]
Thanks a lot that works! I am relatively new to c++ so I didn't think it was required to do that. Btw, your videos are really helpful, they provide some really good tips for coding in c++.

Thanks again.
