### ISSUE TITLE
Using dedicated graphics card?

### ISSUE THREAD

**Issue by shinyclaw** [OneLoneCoder/olcPixelGameEngine#127]
https://stackoverflow.com/questions/16823372/forcing-machine-to-use-dedicated-graphics-card

Best regards,
Dominik

**Comment by gurkanctn** [comment]
the title literally sounds like a click-bait. :)

I'd recommend changing it to "using dedicated graphics card".

**Comment by shinyclaw** [comment]
> the title literally sounds like a click-bait. :)
> 
> I'd recommend changing it to "using dedicated graphics card".

Heh, true ;)

**Comment by OneLoneCoder** [comment]
Since there is nothing to this other than a link - im closing.
