### ISSUE TITLE
(Solved) Unresolved external symbols.

### ISSUE THREAD

**Issue by iDm0nz** [OneLoneCoder/olcPixelGameEngine#13]
[SOLVED]
I solved this issue by defining OLC_PGE_APPLICATION.
I'll leave the issue down there tho.

-------------------

Hello,

I've been trying to create my first project using PixelGameEngine to try it and see what I can do with it.
Unfortunately, when compiling on Visual Studio 2017, I've got unresolved external symbols.

Here's the code:
![image](https://user-images.githubusercontent.com/44713527/50385592-7b216700-06d8-11e9-91a7-f56a19559d02.png)

And here's the output (sorry, it's in french but I hope you get the essential):
![image](https://user-images.githubusercontent.com/44713527/50385620-c3d92000-06d8-11e9-88fe-9d345588afbf.png)

How can I fix this?

(Btw, I love your channel, keep it up dude!)

**Comment by YBelikov** [comment]
Hello! I'm trying to create my first project using pixel game engine but also have same problems as you, IDm0nz. Could you explain how it solves more detailed? I use Visual Studio 17 on Windows 10.  

> [SOLVED]
> I solved this issue by defining OLC_PGE_APPLICATION.
> I'll leave the issue down there tho.
> 
> Hello,
> 
> I've been trying to create my first project using PixelGameEngine to try it and see what I can do with it.
> Unfortunately, when compiling on Visual Studio 2017, I've got unresolved external symbols.
> 
> Here's the code:
> ![image](https://user-images.githubusercontent.com/44713527/50385592-7b216700-06d8-11e9-91a7-f56a19559d02.png)
> 
> And here's the output (sorry, it's in french but I hope you get the essential):
> ![image](https://user-images.githubusercontent.com/44713527/50385620-c3d92000-06d8-11e9-88fe-9d345588afbf.png)
> 
> How can I fix this?
> 
> (Btw, I love your channel, keep it up dude!)



> [SOLVED]
> I solved this issue by defining OLC_PGE_APPLICATION.
> I'll leave the issue down there tho.
> 
> Hello,
> 
> I've been trying to create my first project using PixelGameEngine to try it and see what I can do with it.
> Unfortunately, when compiling on Visual Studio 2017, I've got unresolved external symbols.
> 
> Here's the code:
> ![image](https://user-images.githubusercontent.com/44713527/50385592-7b216700-06d8-11e9-91a7-f56a19559d02.png)
> 
> And here's the output (sorry, it's in french but I hope you get the essential):
> ![image](https://user-images.githubusercontent.com/44713527/50385620-c3d92000-06d8-11e9-88fe-9d345588afbf.png)
> 
> How can I fix this?
> 
> (Btw, I love your channel, keep it up dude!)

**Comment by tzanislav** [comment]
In the header file add:

#define OLC_PGE_APPLICATION
somewhere like in the picture

![Screenshot 2021-02-23 221448](https://user-images.githubusercontent.com/32868846/108902282-95db2780-7624-11eb-8077-46b1c7926871.png)

**Comment by tzanislav** [comment]
> Hello! I'm trying to create my first project using pixel game engine but also have same problems as you, IDm0nz. Could you explain how it solves more detailed? I use Visual Studio 17 on Windows 10.
> 
> > [SOLVED]
> > I solved this issue by defining OLC_PGE_APPLICATION.
> > I'll leave the issue down there tho.
> > Hello,
> > I've been trying to create my first project using PixelGameEngine to try it and see what I can do with it.
> > Unfortunately, when compiling on Visual Studio 2017, I've got unresolved external symbols.
> > Here's the code:
> > ![image](https://user-images.githubusercontent.com/44713527/50385592-7b216700-06d8-11e9-91a7-f56a19559d02.png)
> > And here's the output (sorry, it's in french but I hope you get the essential):
> > ![image](https://user-images.githubusercontent.com/44713527/50385620-c3d92000-06d8-11e9-88fe-9d345588afbf.png)
> > How can I fix this?
> > (Btw, I love your channel, keep it up dude!)
> 
> > [SOLVED]
> > I solved this issue by defining OLC_PGE_APPLICATION.
> > I'll leave the issue down there tho.
> > Hello,
> > I've been trying to create my first project using PixelGameEngine to try it and see what I can do with it.
> > Unfortunately, when compiling on Visual Studio 2017, I've got unresolved external symbols.
> > Here's the code:
> > ![image](https://user-images.githubusercontent.com/44713527/50385592-7b216700-06d8-11e9-91a7-f56a19559d02.png)
> > And here's the output (sorry, it's in french but I hope you get the essential):
> > ![image](https://user-images.githubusercontent.com/44713527/50385620-c3d92000-06d8-11e9-88fe-9d345588afbf.png)
> > How can I fix this?
> > (Btw, I love your channel, keep it up dude!)

In the header file add:
#define OLC_PGE_APPLICATION
somewhere

![Screenshot 2021-02-23 221448](https://user-images.githubusercontent.com/32868846/108902442-c327d580-7624-11eb-97a1-2b9dcde46d8f.png)

**Comment by gorbit99** [comment]
Don't do it in the header file, have it be at the very top of your main file, and definitely not inside the engine itself

**Comment by ElusiveTau** [comment]
> Don't do it in the header file, have it be at the very top of your main file, and definitely not inside the engine itself

Also, make sure that `#define OLC_PGE_APPLICATION` comes before `#include "olcPixelGameEngine.h"`.
