### ISSUE TITLE
DungeonWarping draws decals mirrored

### ISSUE THREAD

**Issue by Chekr** [OneLoneCoder/olcPixelGameEngine#131]
The demo in OneLoneCoder_PGE_DungeonWarping.cpp is drawing the on the tiles Decals in reverse x-axis. I checked the YouTube video as well. The images are drawn mirrored compared to the tiles displayed on the tile selector.

**Comment by OneLoneCoder** [comment]
Correct - probably the projection does a sneaky y-axis invert by mistake.
