### ISSUE TITLE
added a getElapsedTimeto avoid passing it all over subsequent game objects as parameter

### ISSUE THREAD

**Issue by Urigald** [OneLoneCoder/olcPixelGameEngine#133]
Hi, sorry I don't know how to make pullrequest, and I could'nt figure it out tonight either.

So with the suggestion of an active member of the community, I humbly and knowingly come on the wrong page of this github to post this ::
I first suggested this on Discord to have some feedback, and I did from SaladinAkara, who suggested that I made some tests as to consistency between the two methods (passing argument to functions, or simply giving the engine a getter). And the result is : we pass the exact same number (see discord/pixel-game-engine 06.06.20 02:16 am paris time).

Putting this snippet directly in OnUserUpdate() or in a nested function accessing a pointer to the PixelGameEngine instance, like in this case, demonstrates that :
```
std::cout << "fElapsedTime as an arg  : " << fElapsedTime << " -- " << std::endl;
std::cout << "Now from pge->getElapsedTime() : " << pge->getElapsedTime() << " -- " << std::endl;
std::cout << " ---------------------------------------------------------------------------------- " << std::endl;
```

My post on discord, screenshot will be provided under that post.
----------------------------------------------------------------------------------------------
Tonight, I got tired of passing fElapsedTime through every nook and cranny of the game objects.

So I made it a private member right under fFrameTimer :
`float        fElapsedTime          = 0.0f;`

And removed the "float" type keyword before its first use :
```
// float fElapsedTime = elapsedTime.count();
// BECOMES ----->>>
fElapsedTime = elapsedTime.count();
```

And added a getter :
```
// DECLARATION
// Gets the current fElapsedTime
float getElapsedTime();
// IMPLEMENTATION
float PixelGameEngine::getElapsedTime()
{ return fElapsedTime; }
```

Since I populated each of my game objects with a pointer to pge as a member, now I can call from anywhere pge->getElapsedTime(), like any other function of the engine, as desceibed in the Multiple Files Project Wikipage.
![unknown](https://user-images.githubusercontent.com/63999552/83931581-c54bba80-a79d-11ea-8615-c728ec64bab9.png)

**Comment by OneLoneCoder** [comment]
This has been a popular request. Its in 2.06 but I personally wont use it. I like the semantic of propagating time into objects when and where they need it, also this way time can be modified easily - a powerful debugging tool when you need to step through code but time cant assume large values, plus you get the ability to speed up and slow down global time in one place.
