### ISSUE TITLE
How do resource packs work?

### ISSUE THREAD

**Issue by Souna** [OneLoneCoder/olcPixelGameEngine#134]
I'd like to create a small little game with PGE but I'm trying to figure out how I could package my assets. It's going to start small but I want to be able to just keep adding and adding assets as time goes by, without it getting out of hand.

Do I use the resource packs class for this? I can't really understand how it works. If anyone knows and would like to explain it to me I'd appreciate it. I'm asking because the tutorial wiki hasn't been updated to explain the Resource Packs yet

Thanks

**Comment by OneLoneCoder** [comment]
The tutorial will be up soon, but dont worry about them unless you know you need them, and even then, adding them in after is trivial. you can prep for their usage by always loading your resources like this
```cpp
// Where you load your stuff
olc::ResourcePack rpack = nullptr;

// When you load things
some_sprite = new olc:;Sprite("Path/To/Sprite.png", rpack);
```
This way when the tutorial goes up, your code is ready to use them. In principle a resource pack is a virtual file system, if its nullptr, then the PGE goes and looks on your HDD, if it isnt, then it looks for that location in the pack. This way you can keep the same paths, which makes it easy to debug and build.
