### ISSUE TITLE
compilation problen

### ISSUE THREAD

**Issue by vitecd** [OneLoneCoder/olcPixelGameEngine#143]
Hi,
I've been installed fresh 2019 MSVC 2019 community version. Tried to compile example:
OneLoneCoder_PGE_8BitsImProc.cpp(65,10): fatal error C1083: Cannot open include file: 'escapi.h': No such file or directory
and many similar to
OneLoneCoder_PGE_Balls2.cpp(174,78): warning C4244: 'argument': conversion from 'int32_t' to 'float', possible loss of data
Cuold you help me to fix shortly please?

**Comment by vitecd** [comment]
escapi found
I have a next problem
1>------ Build started: Project: GE, Configuration: Debug Win32 ------
1>GE.cpp
1>GE.obj : error LNK2019: unresolved external symbol "public: bool __thiscall olc6502::complete(void)" (?complete@olc6502@@QAE_NXZ) referenced in function "private: virtual bool __thiscall Demo_olc2C02::OnUserUpdate(float)" (?OnUserUpdate@Demo_olc2C02@@EAE_NM@Z)
1>GE.obj : error LNK2019: unresolved external symbol "public: class std::map<unsigned short,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<unsigned short>,class std::allocator<struct std::pair<unsigned short const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > __thiscall olc6502::disassemble(unsigned short,unsigned short)" (?disassemble@olc6502@@QAE?AV?$map@GV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$less@G@2@V?$allocator@U?$pair@$$CBGV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@std@@@2@@std@@GG@Z) referenced in function "private: virtual bool __thiscall Demo_olc2C02::OnUserCreate(void)" (?OnUserCreate@Demo_olc2C02@@EAE_NXZ)
1>GE.obj : error LNK2019: unresolved external symbol "public: __thiscall Cartridge::Cartridge(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0Cartridge@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "void __cdecl std::_Construct_in_place<class Cartridge,char const (&)[12]>(class Cartridge &,char const (&)[12])" (??$_Construct_in_place@VCartridge@@AAY0M@$$CBD@std@@YAXAAVCartridge@@AAY0M@$$CBD@Z)
1>GE.obj : error LNK2019: unresolved external symbol "public: __thiscall Cartridge::~Cartridge(void)" (??1Cartridge@@QAE@XZ) referenced in function "public: void * __thiscall Cartridge::`scalar deleting destructor'(unsigned int)" (??_GCartridge@@QAEPAXI@Z)
1>GE.obj : error LNK2019: unresolved external symbol "public: bool __thiscall Cartridge::ImageValid(void)" (?ImageValid@Cartridge@@QAE_NXZ) referenced in function "private: virtual bool __thiscall Demo_olc2C02::OnUserCreate(void)" (?OnUserCreate@Demo_olc2C02@@EAE_NXZ)
1>GE.obj : error LNK2019: unresolved external symbol "public: class olc::Sprite & __thiscall olc2C02::GetScreen(void)" (?GetScreen@olc2C02@@QAEAAVSprite@olc@@XZ) referenced in function "private: virtual bool __thiscall Demo_olc2C02::OnUserUpdate(float)" (?OnUserUpdate@Demo_olc2C02@@EAE_NM@Z)
1>GE.obj : error LNK2019: unresolved external symbol "public: __thiscall Bus::Bus(void)" (??0Bus@@QAE@XZ) referenced in function "public: __thiscall Demo_olc2C02::Demo_olc2C02(void)" (??0Demo_olc2C02@@QAE@XZ)
1>GE.obj : error LNK2019: unresolved external symbol "public: __thiscall Bus::~Bus(void)" (??1Bus@@QAE@XZ) referenced in function __unwindfunclet$??0Demo_olc2C02@@QAE@XZ$1
1>GE.obj : error LNK2019: unresolved external symbol "public: void __thiscall Bus::insertCartridge(class std::shared_ptr<class Cartridge> const &)" (?insertCartridge@Bus@@QAEXABV?$shared_ptr@VCartridge@@@std@@@Z) referenced in function "private: virtual bool __thiscall Demo_olc2C02::OnUserCreate(void)" (?OnUserCreate@Demo_olc2C02@@EAE_NXZ)
1>GE.obj : error LNK2019: unresolved external symbol "public: void __thiscall Bus::reset(void)" (?reset@Bus@@QAEXXZ) referenced in function "private: virtual bool __thiscall Demo_olc2C02::OnUserCreate(void)" (?OnUserCreate@Demo_olc2C02@@EAE_NXZ)
1>GE.obj : error LNK2019: unresolved external symbol "public: void __thiscall Bus::clock(void)" (?clock@Bus@@QAEXXZ) referenced in function "private: virtual bool __thiscall Demo_olc2C02::OnUserUpdate(float)" (?OnUserUpdate@Demo_olc2C02@@EAE_NM@Z)

**Comment by gurkanctn** [comment]
This is the most famous problem, and the solution is to declare your application as olcPixelGameEngine at the start of the file.

e.g.
`#define OLC_PGE_APPLICATION`

**Comment by vitecd** [comment]
this line is present, as soon I'm just trying to compile sources downloaded from this repository

**Comment by vitecd** [comment]
> This is the most famous problem

where I can read about them?

**Comment by vitecd** [comment]
Finally, after hours of googling, after read this https://stackoverflow.com/questions/28653316/error-lnk2019-unresolved-external-symbol-public-thiscall-constructor-issu
I've been deleted all the old temporary files, create a new project, and add all the source files to the project. now compiled with no problems yet ))
