### ISSUE TITLE
when using the GetKey function down, right, s, d keys do not get detected

### ISSUE THREAD

**Issue by poyking** [OneLoneCoder/olcPixelGameEngine#144]

**Comment by gurkanctn** [comment]
Can you give some details?

Does it work for other keys?

Do you use .bHeld, .bReleased, .bPressed?

**Comment by poyking** [comment]
I use .bHeld
here is the code:
if (GetKey(olc::Key::D).bHeld)x = x + 0.0002;
if (GetKey(olc::Key::A).bHeld)x = x - 0.0002;
if (GetKey(olc::Key::W).bHeld)y = y - 0.0002;
if (GetKey(olc::Key::S).bHeld)y = y + 0.0002;

**Comment by gurkanctn** [comment]
Your title says "down" key, but you're checking D-A-W-S keys.

1) Make sure that your code section is running inside "onuserupdate" function, not somewhere else.
2) try adding a BreakPoint to the first line (checking D), and see if x is updated or not,
3) Alternatively, you can print out the value of x (is it a float?). if x is an integer, your keys might not work.
4) You need a space between closing parantheses and x. (possibly, it's github's formatting that caused the space to disappear).
5) here's my line, reading user input to update a value:

`if (GetKey(olc::Key::A).bHeld) Player.vx -= Player.speed * fElapsedTime; //accelerate LEFT`

**Comment by poyking** [comment]
fixed the value of x was an integer
