### ISSUE TITLE
olcPGEX_Sound doesn't work correctly

### ISSUE THREAD

**Issue by IconLivin** [OneLoneCoder/olcPixelGameEngine#146]
I wanted to use a sound in my amazing pixel game, so I tried to use example to figure out how sound works in OLC, but I got this ERROR, another errors is refers to that one: 	namespace "olc" has no member "ResourceBuffer" olcPGEX_Sound.h	297. And this error is actually right, OLC doesn't have member ResourceBuffer. Fix it please. Best wishes.

**Comment by Moros1138** [comment]
have you included the pixel game engine header BEFORE including the sound extension header?

if not, that's probably contributing to your problem.

**Comment by IconLivin** [comment]
#define OLC_PGE_APPLICATION
#include "olcPixelGameEngine.h"

#define OLC_PGEX_SOUND
#include "olcPGEX_Sound.h"

Here is an order. As you can see, it is in a right order. More than ResourceBuffer is not a part of this header either.

**Comment by Moros1138** [comment]
can you post the errors you are getting, also details like what compiler? what version of the compiler? the OS you're on? and any other details you think might provide more insight.

**Comment by IconLivin** [comment]
ERRORS:

1. E0135	namespace "olc" has no member "ResourceBuffer" olcPGEX_Sound.h	297	
2. E0135	class "olc::ResourcePack" has no member "GetFileBuffer" olcPGEX_Sound.h	297	
3. C2039	'ResourceBuffer': is not a member of 'olc' olcpgex_sound.h	297	
4. C2065	'ResourceBuffer': undeclared identifier olcpgex_sound.h	297	
5. C2146	syntax error: missing ';' before identifier 'rb' olcpgex_sound.h 297	
6. C2065	'rb': undeclared identifier olcpgex_sound.h	297	
7. C2039	'GetFileBuffer': is not a member of 'olc::ResourcePack' olcpgex_sound.h 297	
8. C2065	'rb': undeclared identifier olcpgex_sound.h	298	

OS: Windows 10 64-bit
Compiler: ISO C++17 Standard (/std:c++17)

**Comment by Moros1138** [comment]
Open olcPixelGameEngine.h and check that you're using the latest available version, which is v2.06

**Comment by scripticuk** [comment]
Are you by any chance spreading your application over multiple files? If so, you'll need to add your includes differently depending on what file you're looking at.

For example, let's say you have three files, namely the **main.cpp**, **mygame.cpp** (your PGE implementation) and **mygame.h**.

Your main.cpp file should have the includes like this:
`#define OLC_PGE_APPLICATION
#include "olcPixelGameEngine.h"

#define OLC_PGEX_SOUND
#include "olcPGEX_Sound.h"`

Your mygame.h file however should look like this:
`#include "olcPixelGameEngine.h"
#include "olcPGEX_Sound_updated.h"`

My guess is this is where you're going wrong, although it's hard to tell without seeing your code.

**Comment by Moros1138** [comment]
If he were multi-file he would be getting duplicate defintion errors instead he's getting undeclared. The only reason I can think of that this is a problem is he's using a version of PGE that doesn't have the ResourcePack class.

Resource packs were added December 12, 2018 in v1.11.

**Comment by IconLivin** [comment]
Version is 1.20, but I downloaded the latest version. Where can I get v2.06?
Also I don't have multiple files, only header files of OLC and main.cpp

**Comment by Moros1138** [comment]
You went into the "Last Version" folder.. the intent of Javid was that mean "Previous Version" the Latest version is in the root of the repository.
