### ISSUE TITLE
Compilation dependencies for arch-based linux distribution

### ISSUE THREAD

**Issue by Annwan** [OneLoneCoder/olcPixelGameEngine#149]
I had succeess compiling on an Arch-linux system with the following dependencies (inferred from preexisting ubuntu requirements)

 - `gcc` (gcc and g++)
 - `glibc` (gnu libc)
 - `libpng`
 - `mesa` (OpenGl)

the command to update the datapase is `sudo pacman -Sy`
the command to install packages is `sudo pacman -S <package list>`

So you can install everything required with
```
sudo pacman -Sy
sudo pacman -S gcc glibc libpng mesa
```

**Comment by Annwan** [comment]
If someone with write permission to the wiki can do something to update it, it would be great

**Comment by Moros1138** [comment]
I have added those instructions to the wiki page! Thank you very much for your contribution!

https://github.com/OneLoneCoder/olcPixelGameEngine/wiki/Compiling-on-Linux
