### ISSUE TITLE
How to use in c#

### ISSUE THREAD

**Issue by Gionson13** [OneLoneCoder/olcPixelGameEngine#150]
In the README file it says that it is implemented in other languages: c#, java, lua and rust.
How can I use it in those languages (I'm more interested in c#)?

**Comment by RodizzGamer** [comment]
i think you have to export to dll

**Comment by mandar1jn** [comment]
It says it is reimplement wich means that it is recreated in c# I think

**Comment by OneLoneCoder** [comment]
Yes, there are ports for specific languages, or wrap this one up in DLL, with an appropriate interface (not a small job im afraid)

**Comment by toman222** [comment]
Are there any links to the ports?
I've so far only found an archived C# repository
