### ISSUE TITLE
Question on resize

### ISSUE THREAD

**Issue by demonicmetalcs** [OneLoneCoder/olcPixelGameEngine#151]
When you use the construct function the following line is there
`vInvScreenSize = { 1.0f / float(screen_w), 1.0f / float(screen_h) };`

But in the void PixelGameEngine::SetScreenSize(int w, int h) this line is not there.

When i embedded the PGE into c# winform i use this function to set the screen size, but decals don't work.
When I added the line decals worked again, I am i doing something wrong or have i found a bug?

**Comment by OneLoneCoder** [comment]
Yup, a little bug, i'll add it for 2.08 - Thanks!
