### ISSUE TITLE
undefined reference to `olc::PixelGameEngine::Construct(int, int, int, int, bool, bool)'

### ISSUE THREAD

**Issue by realszopen** [OneLoneCoder/olcPixelGameEngine#154]
When trying to compile a simple example I'm getting the below errors list:

`/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/ccKWLqXb.o: in function `main':
myOwnExample.cpp:(.text+0x47): undefined reference to `olc::PixelGameEngine::Construct(int, int, int, int, bool, bool)'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: myOwnExample.cpp:(.text+0x63): undefined reference to `olc::PixelGameEngine::Start()'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/ccKWLqXb.o: in function `__static_initialization_and_destruction_0(int, int)':
myOwnExample.cpp:(.text+0x100): undefined reference to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: myOwnExample.cpp:(.text+0x11f): undefined reference to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: myOwnExample.cpp:(.text+0x13e): undefined reference to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: myOwnExample.cpp:(.text+0x15d): undefined reference to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: myOwnExample.cpp:(.text+0x17c): undefined reference to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/ccKWLqXb.o:myOwnExample.cpp:(.text+0x19b): more undefined references to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)' follow
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/ccKWLqXb.o: in function `Example::Example()':
myOwnExample.cpp:(.text._ZN7ExampleC2Ev[_ZN7ExampleC5Ev]+0x15): undefined reference to `olc::PixelGameEngine::PixelGameEngine()'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: myOwnExample.cpp:(.text._ZN7ExampleC2Ev[_ZN7ExampleC5Ev]+0x47): undefined reference to `olc::PixelGameEngine::~PixelGameEngine()'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/ccKWLqXb.o: in function `Example::OnUserUpdate(float)':
myOwnExample.cpp:(.text._ZN7Example12OnUserUpdateEf[_ZN7Example12OnUserUpdateEf]+0x27): undefined reference to `olc::PixelGameEngine::ScreenWidth()'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: myOwnExample.cpp:(.text._ZN7Example12OnUserUpdateEf[_ZN7Example12OnUserUpdateEf]+0x48): undefined reference to `olc::PixelGameEngine::ScreenHeight()'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: myOwnExample.cpp:(.text._ZN7Example12OnUserUpdateEf[_ZN7Example12OnUserUpdateEf]+0xb7): undefined reference to `olc::Pixel::Pixel(unsigned char, unsigned char, unsigned char, unsigned char)'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/ccKWLqXb.o:(.rodata._ZTV7Example[_ZTV7Example]+0x30): undefined reference to `olc::PixelGameEngine::OnUserDestroy()'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/ccKWLqXb.o:(.rodata._ZTV7Example[_ZTV7Example]+0x38): undefined reference to `olc::PixelGameEngine::Draw(int, int, olc::Pixel)'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/ccKWLqXb.o: in function `Example::~Example()':
myOwnExample.cpp:(.text._ZN7ExampleD2Ev[_ZN7ExampleD5Ev]+0x20): undefined reference to `olc::PixelGameEngine::~PixelGameEngine()'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /tmp/ccKWLqXb.o:(.rodata._ZTI7Example[_ZTI7Example]+0x10): undefined reference to `typeinfo for olc::PixelGameEngine'
collect2: error: ld returned 1 exit status
`

My code below:

`#include "olcPixelGameEngine.h"

class Example : public olc::PixelGameEngine {
	public:
	Example() {
		sAppName = "Example";
	}
	bool OnUserCreate() override {
		return true;
	}
	bool OnUserUpdate(float fElapsedTime) override {
		for (int x = 0; x < ScreenWidth(); x++) {
			for (int y = 0; x < ScreenHeight(); y++) {
				Draw(x, y, olc::Pixel(rand() % 256, rand() % 256, rand() % 256));
			}
		}
		return true;
	}
};

int main() {
	Example demo;
	if (demo.Construct(256, 240, 4, 4)) {
		demo.Start();
	}
	return 0;
}`

I'm compiling on OpenSUSE Tumbleweed with the below command:

`g++ -o myOwnExample ./myOwnExample.cpp -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17`

I believe all necessary packages are installed but apparently something is going not the right way.

**Comment by Moros1138** [comment]
You are getting ``undefined reference`` errors for PGE functions because you are failing to include the implementation.

before your ``#include`` directive for the PGE header you need to ``#define OLC_PGE_APPLICATION`` like so.

```
#define OLC_PGE_APPLICATION
#include "olcPixelGameEngine.h"
```

**Comment by realszopen** [comment]
Thank you. Code compiles just fine, the app seems to start, however it simply hangs. It could be the system issue.

**Comment by realszopen** [comment]
Simple bugs in my code, have not noticed them before, all done and fixed.
