### ISSUE TITLE
Velocity of 0 on one axis results in no collision

### ISSUE THREAD

**Issue by Qlii256** [OneLoneCoder/olcPixelGameEngine#155]
When using the RayVsRect functionality from the [Arbitrary Rectangle Collision Detection & Resolution - Complete!](https://www.youtube.com/redirect?q=https%3A%2F%2Fgithub.com%2FOneLoneCoder%2FolcPixelGameEngine%2Fblob%2Fmaster%2FVideos%2FOneLoneCoder_PGE_Rectangles.cpp&redir_token=QUFFLUhqbVpISl8xaUlvMk1Rd3lFaHBweVA3ZVVnNnItUXxBQ3Jtc0tuRGlrR3FiMHV5RzJ0UmtVelZvSWlJck9Ca2xGX3I1dC1NdXpHempobWpXa2M2d19Va09Qdjl6OFVGMXBkcXFJcnIxSVVNQlpqUk5yMTlYU3BmS2lGdGo1c21OOGstaXFRdTVwVGNkLS1QcDBHNnhvcw%3D%3D&event=video_description&v=8JJ-4JgR7Dg) video, it returns false (no collision) when one or both of the axis on the velocity are 0. When moving left in a straight line, the y-axis is 0, but there's still the possibility of colliding with another rect. This has something to do with division by zero, but I can't come up with a solution to get the correct direction when 0 is passed. Any ideas on how to fix this?

**Comment by OneLoneCoder** [comment]
I guess you could just check if its 0 no?
