### ISSUE TITLE
How to compile on Raspberry Pi

### ISSUE THREAD

**Issue by BluishRed** [OneLoneCoder/olcPixelGameEngine#158]
Hello,

I am extremely new to programming and i would appreciate some help on installing olcPGE. I have no idea where to start or what to do, a detailed response would be appreciated as i have no real experience with any of this. 

P.S. Can you use any IDE to run this?

Thank you so much

**Comment by dragoneye65** [comment]
Before we can even begin to help you with this, as there is more than 20 different operating systems you can install on a Raspery Pi it would be very helpful to include that information.

**Comment by dragoneye65** [comment]
If you have installed a Linux distribution OS, you could do well following the Linux install guide.
https://github.com/OneLoneCoder/olcPixelGameEngine/wiki/Compiling-on-Linux

**Comment by BluishRed** [comment]
@dragoneye65 Thank you for the quick reply, i am using Raspbian which is based on Debian. Therefore both of the instructions i think won't work. What should i do instead?

**Comment by dragoneye65** [comment]
If you are using a Debian based Linux distribution, then that instruction is perfect as it is made for Debian based distros. ;-)

**Comment by Jachdich** [comment]
I can run a fairly complex application with no modifications on the raspberry pi. Just follow the linux guide like it was any other device.
