### ISSUE TITLE
Some instances of `Pixel` in signatures are not prepended with `olc::`

### ISSUE THREAD

**Issue by joshinils** [OneLoneCoder/olcPixelGameEngine#159]
Not a bug.
I noticed this since my code is not in the `olc` namespace, so when I copied a signature that got me an error.

One such example: https://github.com/OneLoneCoder/olcPixelGameEngine/blob/a8dd6096e6345e76cc2ab62b9b95505b76b9a71f/olcPixelGameEngine.h#L802

I want to point this out since almost all other instances do have the `olc` namespace prepended and thus this is not consistent either way.

**Comment by OneLoneCoder** [comment]
I dont entirely trust the "copy signature" function. Very few people's code is in the olc namespace, including my own, and it hasnt been a problem before. I think its just VS not getting it quite right.

**Comment by toman222** [comment]
I think the complaint was just inconsistency with `Pixel` vs `olc::Pixel`?
The line below the quoted one says `olc::Pixel`
