### ISSUE TITLE
Shlwapi.h header should prefer lowercase

### ISSUE THREAD

**Issue by Cecilectomy** [OneLoneCoder/olcPixelGameEngine#161]
https://github.com/OneLoneCoder/olcPixelGameEngine/blob/a8dd6096e6345e76cc2ab62b9b95505b76b9a71f/olcPixelGameEngine.h#L3011

This include should be preferred to be `#include <shlwapi.h>` (all lowercase) due to host case-sensitivity compatibility. When cross compiling for Windows from a Linux Host using mingw, the current include fails to find the proper header. It is found and included properly if changed to all lowercase. I have tested and confirmed this change seems to be working on Windows using Visual Studio 2019 and MSYS2 MinGW, and on Linux (Debian Buster and Ubuntu 20.04) using MinGW w64.

**Comment by dandistine** [comment]
The actual file name on Windows (Confirmed headers for 10.0.17763.0) is "Shlwapi.h" with the capital S.

**Comment by Cecilectomy** [comment]
@dandistine, The actual casing of the header on windows is irrelevant, nor is it being contested (I know that the casing is capitalized on Windows). As stated in the ticket, windows' filesystem is case insensitive (normally) and does not matter whether the usage is capitalized or lowercase, however, on Linux it **IS** case sensitive, and the header when compiling from linux using mingw is lowercase. As such, for cross compilation compatibility, the usage here should be **preferred** to be lowercase, and will continue to work for windows as well as allow cross compilation from Linux to Windows. It is fairly standard to do this due to this issue.

**Comment by Cecilectomy** [comment]
Just as an extra note, the olcPixelGameEngine.h header is already doing this for another header that is capitalized on windows, "Windows.h".
https://github.com/OneLoneCoder/olcPixelGameEngine/blob/a8dd6096e6345e76cc2ab62b9b95505b76b9a71f/olcPixelGameEngine.h#L2716
https://github.com/OneLoneCoder/olcPixelGameEngine/blob/a8dd6096e6345e76cc2ab62b9b95505b76b9a71f/olcPixelGameEngine.h#L3009
https://github.com/OneLoneCoder/olcPixelGameEngine/blob/a8dd6096e6345e76cc2ab62b9b95505b76b9a71f/olcPixelGameEngine.h#L3326

**Comment by OneLoneCoder** [comment]
Agreed. Will include in next version
