### ISSUE TITLE
Ray   from rectangles video

### ISSUE THREAD

**Issue by fossegutten** [OneLoneCoder/olcPixelGameEngine#162]
Line 117 in OneLoneCoder_PGE_Rectangles.cpp

Should this line:
`if (t_hit_far < 0)`
be this instead?
`if (t_hit_near < 0)` ?

I just want to mention that i made this code in C#, but i got Infinity values from t_hit_far, and it still checked for collisions behind. I  changed to t_hit_near and it seems to work fine now. Not sure if this applies to C++

**Comment by OneLoneCoder** [comment]
Im unsure how C# handles infinity, but in C++ you get +/- infinity which can be tested against 0.
