### ISSUE TITLE
DrawDecal is rendering a white image when called from a object pointer

### ISSUE THREAD

**Issue by kishorecmg** [OneLoneCoder/olcPixelGameEngine#165]
Greetings, everyone.
I have came across this strange issue. I tried to call DrawDecal() function from a class that is not directly derived from olc::PixelGameEngine, so I tried to use the above function using a pointer that points to the main class. DrawDecal() renders white image, but DrawSprite() renders the image correctly even when called using a pointer. 

![image](https://user-images.githubusercontent.com/64677483/91582381-5e3d3c80-e96d-11ea-9ec5-bd521d984ac5.png)
(Like the above image)

![image](https://user-images.githubusercontent.com/64677483/91582132-00a8f000-e96d-11ea-8d76-b70f953bb9eb.png)

But when I used DrawDecal() from the main class, it renders the image correctly.

![image](https://user-images.githubusercontent.com/64677483/91582488-85940980-e96d-11ea-9623-a98cbab93761.png)
(This class is derived directly from PixelGameEngine)

![image](https://user-images.githubusercontent.com/64677483/91582600-aa887c80-e96d-11ea-95bc-552ac1cc1f7a.png)

Am I doing something wrong? Or is this how it should be? Please help.

**Comment by OneLoneCoder** [comment]
This entirely depends upon when your dino object is being constructed. If you are constructing it before the engine has started it cant upload the texture to the GPU, thus it will be white.

**Comment by kishorecmg** [comment]
You are right. I made a mistake by loading the dino decal on the constructor of the Dino class, which is defined before OnUserCreate() function. So, I had to create a new function init() which contains decal definitions in Dino class and then calling it from OnUserCreate() function.

Thank you for your time.
