### ISSUE TITLE
trouble using OnUserCreate ...... Plz Help 

### ISSUE THREAD

**Issue by pavan-0328** [OneLoneCoder/olcPixelGameEngine#167]
I'am trying to make a clone of pong with my c++ knowledge using pixel game engine
when i  assigning valus for balls pos in OnUserCreate  and trying to use them in OnUserUpdate iam getting a error as variable not declared in this scope

help me (i'am using kali linux os)

**Comment by piotrwyrw** [comment]
Did you declare you variables inside of OnUserCreate scope?
The best way is to declare all of your variables in the class.

**Comment by pavan-0328** [comment]
Thank you!
