### ISSUE TITLE
ResourcePacks wiki not yet available

### ISSUE THREAD

**Issue by Aerofoyle** [OneLoneCoder/olcPixelGameEngine#168]
Loving the PGE - I'm reliving my youth by creating 1980s style games.
I have a lot of PNG image files, and I'd like to embed them as resources in the executable.
There is probably a way to do this with the existing features, but I can't quite figure it out.
I assume it is something to do with ResourcePacks.  It would be great to get some documentation on embedding resources.

Actually it isn't the embedding bit that is the problem, I can do that with Visual Studio.  How do I get the embedded PNG data into a Sprite?

Cheers - great work.

**Comment by kishorecmg** [comment]
#134 

Please refer above issue.

```
> // Where you load your stuff
> olc::ResourcePack *rpack = nullptr;
> 
> // When you load things
> some_sprite = new olc::Sprite("Path/To/Sprite.png", rpack);
```

For time being, please refer this answer. Just remember to use full address for your PNG images, like "C:\\Users\\~"

**Comment by Aerofoyle** [comment]
> #134
> 
> Please refer above issue.
> 
> ```
> > // Where you load your stuff
> > olc::ResourcePack *rpack = nullptr;
> > 
> > // When you load things
> > some_sprite = new olc::Sprite("Path/To/Sprite.png", rpack);
> ```
> 
> For time being, please refer this answer. Just remember to use full address for your PNG images, like "C:\Users\~"

Sorry, this is not doing what I need.  Is this embedding the resources?  I can do that already.  I want to retrieve the resources without having the individual files available.

**Comment by OneLoneCoder** [comment]
Hi it wont be long, Ive clocked this and getting something thrown together. Though if you have created a resource pack, to use it, simply load it, and pass the pointer to your Sprite() constructor, or GetResourceBuffer to access the memory stream of the file.

**Comment by Moros1138** [comment]
the answer skips the part where you actually load the resource pack here's a more complete answer

```
// give us a resource pack object
olc::ResourcePack *rpack = nullptr;

// load our resource pack
rpack->Load("Path/To/Packed/File.pak"); 

// When you load things
some_sprite = new olc::Sprite("Path/To/Sprite.png", rpack);
```
