### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by cppmadguy** [OneLoneCoder/olcPixelGameEngine#169]
Hello !
I am compiling with g++ 9.2.0 on windows 10, and I get an error when compiling the example project:

<experimental\filesystem> no such file or directory at line 288

I've lookod up online and it seems that it is not availlable on windows with GCC.

Is there any quick fixes to that problem ?

**Comment by cppmadguy** [comment]
I saw that the pull request #56 was about to fix this problem under MSVC, I think this show that this problem is not only due to compiler configuration.

**Comment by OneLoneCoder** [comment]
Have you ensured you are compiling with -std=c++17?

**Comment by cppmadguy** [comment]
Yes, I alway use this flag. I call it straight from the command line, it us not used by any IDE.

**Comment by cppmadguy** [comment]
After reinstalling GCC and making sure I used the flag -std=c++17, a few errors came out. Interestingly even if I include the thread file before including the PGE they still showed up.
![image](https://user-images.githubusercontent.com/70852924/92476933-0362db00-f1e0-11ea-8395-45704e778a17.png)

**Comment by cppmadguy** [comment]
Here is my compilation command by the way: g++ -std=c++17 src\olcTest.cpp -o bin\prog.exe -I include

**Comment by matt-hayward** [comment]
I believe the compile command should be:

```
g++ -o YourProgName YourSource.cpp -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17
```

**Comment by cppmadguy** [comment]
This did not resolve any issue. I get the exact same errors. But thanks for the help anyway !

**Comment by Moros1138** [comment]
> I believe the compile command should be:
> 
> ```
> g++ -o YourProgName YourSource.cpp -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17
> ```

**Comment by Moros1138** [comment]
I'm bad at github mobile apparently.

run ``gcc -v`` and show us the output. I suspect you have a bad version of mingw

**Comment by cppmadguy** [comment]
![image](https://user-images.githubusercontent.com/70852924/92722577-17d1df80-f368-11ea-8afd-ae2c3bbce660.png)

There it is.

**Comment by Moros1138** [comment]
yup bad version of mingw... I made video to install the correct version.. I suggest removing the bad version first. 

https://github.com/OneLoneCoder/olcPixelGameEngine/wiki/Compiling-on-Windows-with-Other-Compilers

**Comment by cppmadguy** [comment]
thanks gonna try it out now !

**Comment by cppmadguy** [comment]
well, I now have a different set of errors:
![image](https://user-images.githubusercontent.com/70852924/92726695-45ba2280-f36e-11ea-906d-ef49120c055b.png)

**Comment by cppmadguy** [comment]
and here is g++ -v:
![image](https://user-images.githubusercontent.com/70852924/92726834-85810a00-f36e-11ea-8c15-3b02acd22c3a.png)

**Comment by cppmadguy** [comment]
and using the command proposed by matt, I get this:
![image](https://user-images.githubusercontent.com/70852924/92727055-d7c22b00-f36e-11ea-9971-bbecf738f724.png)

**Comment by Moros1138** [comment]
> well, I now have a different set of errors:
> ![image](https://user-images.githubusercontent.com/70852924/92726695-45ba2280-f36e-11ea-906d-ef49120c055b.png)

show me the build command you used for this

**Comment by cppmadguy** [comment]
here it is: g++ -std=c++17 src\olcTest.cpp -o bin\prog.exe -I include

**Comment by Moros1138** [comment]
look at the description of my video, it has the appropriate flags you need to set

**Comment by cppmadguy** [comment]
It worked
