### ISSUE TITLE
Check Bitmap "properly" in return of Gdiplus::Bitmap::FromFile

### ISSUE THREAD

**Issue by zikdoz** [OneLoneCoder/olcPixelGameEngine#17]
That method returns a valid pointer anyways (for "failed" Bitmap too), thus check for nullptr doesn't really do a thing.

[Click here to see a quick solution on Stackoverflow](https://stackoverflow.com/questions/11345491/how-do-i-check-if-gdiplusbitmapfromfile-has-return-a-valid-bitmap)

Basically, you just replace `if (bmp == nullptr)` [here](https://github.com/OneLoneCoder/olcPixelGameEngine/blob/5e1f9c4f3a4ae50fb25610b2e3a0dad267e61b03/olcPixelGameEngine.h#L698)
with `if ( bmp->GetLastStatus() != Gdiplus::Status::Ok )` (or add it)

**Comment by OneLoneCoder** [comment]
OK, This is interesting, thanks zikdoz!
