### ISSUE TITLE
Support for HSV colors

### ISSUE THREAD

**Issue by LightningAA** [OneLoneCoder/olcPixelGameEngine#170]
There are times when it's useful to be able to use HSV (hue, saturation, value) color (like generating a color with a random hue), it'd be nice if there was something like `olc::PixelHSV(int hue, int saturation, int value)` and `olc::PixelHSVF(float hue, float saturation, float value)` like how there is already `PixelF` so you can use floats instead of ints.

**Comment by matt-hayward** [comment]
There's a PR for this in the additional colours PGEX - https://github.com/matt-hayward/olcPGEX_AdditionalColours/pull/2

I'll get around to accepting and merging this in the next few days.

**Comment by matt-hayward** [comment]
This has now been merged and tagged at https://github.com/matt-hayward/olcPGEX_AdditionalColours/releases/tag/v1.0.0

As such, closing this issue.
