### ISSUE TITLE
[Suggestion] Built-in function in RayCastWorld for object movement in arbitrary direction in relation to objects heading

### ISSUE THREAD

**Issue by En1gm4** [OneLoneCoder/olcPixelGameEngine#177]
Right now, when _olc::rcw::Object::Walk()_ and _olc::rcw::Object::Strafe()_ are being used simultaneously, due to the current implementation, the objects velocity vector is simply being overwritten after each of those calls. While this avoids the problem of faster movement along the diagonals, for the object to be moved in both directions, objects _vel_ variable needs to be directly accessed. 

So I suggest adding a function with the following signature: 
_void olc::rcw::Object::Move(olc::vf2d)_ ,
which would natively give this feature to the engine, instead of requiring a proprietary function to be written. This function would calculate the objects new velocity in the game world (new _vel_) taking in the velocity vector relative to the objects frame of reference (using the _fHeading_ ...).

Such a function would be useful when controlling a character with a gamepad where one could just feed the function values from analog stick axes.

This is obviously not a problem with the current engine, it would just add some sugar.

**Comment by OneLoneCoder** [comment]
Its a good idea, and yeah current strafe/walk combination is poor.

**Comment by OneLoneCoder** [comment]
Doing some RCW work now, so will consider this.
