### ISSUE TITLE
Renderer doesn't check if Sprite loaded the file properly

### ISSUE THREAD

**Issue by Zij-IT** [OneLoneCoder/olcPixelGameEngine#179]
```
olc::rcode Renderable::Load(const std::string& sFile, ResourcePack* pack)
    {
        pSprite = std::make_unique<olc::Sprite>();
        if (pSprite->LoadFromFile(sFile, pack))
        {
            pDecal = std::make_unique<olc::Decal>(pSprite.get());
            return olc::rcode::OK;
        }
        else
        {
            pSprite.release();
            pSprite = nullptr;
            return olc::rcode::NO_FILE;
        }
    }
```

**Issue** 
Load returns olc::rcode::OK even if there was no file present with the passed file name.

**Details**
if `(pSprite->LoadFromFile(sFile, pack)` returns `olc::rcode::NO_FILE`, the renderable is still created, instead of returning `olc::rcode::NO_FILE` as expected. 

**Recommended fix**
Changing the faulty if statement to:
`if (pSprite->LoadFromFile(sFile, pack) == olc::rcode::OK)`

**Comment by OneLoneCoder** [comment]
This is a good spot, and thanks for identifying it. I will add it with a credit in next update.
