### ISSUE TITLE
GetMouseWheel on MacOS

### ISSUE THREAD

**Issue by matthew-periut** [OneLoneCoder/olcPixelGameEngine#180]
GetMouseWheel() is completely unimplemented on Mac OS
Attempting to scroll on Mac OS returns the function with zero.

A first-party mouse and trackpad have been tested, and a third party mouse has been tested, but all return zero.

Mac OS Catalina 10.15.6

**Comment by MumflrFumperdink** [comment]
Yes, this is a problem with the library that the mac version of the PGE is built on, GLUT. The original version, which is preinstalled on macOS, does not support a mouse wheel so I left that part of the PGE blank. While there are fixed versions (such as freeglut), the point was to have as few library installations as possible. I have been searching for some kind of alternative low-level library on mac to fix this, but I could not find one that was not 32-bit only or an outside library.

**Comment by matthew-periut** [comment]
Awesome!! What a savior, good work
