### ISSUE TITLE
Destroy or close windows pane is missing.

### ISSUE THREAD

**Issue by jipphysics** [OneLoneCoder/olcPixelGameEngine#186]
I am working on a project that requires opening and closing the window pane. Currently, when I click the exit icon in the windows, the engine stops drawing but the window is not closing. I am working on a linux station. I am not sure how this work but, I see a "XCreateWindow" function, but I don't see a "XDestroyWindow" window function. Is this feature missing?

**Comment by OneLoneCoder** [comment]
I will look into this

**Comment by OneLoneCoder** [comment]
ok, Ive added in an experimental XDestroyWindow - If it gets complaints, I know who to blame :D
