### ISSUE TITLE
Sprite animation with the Raycast world extension

### ISSUE THREAD

**Issue by lysergik** [OneLoneCoder/olcPixelGameEngine#187]
Hi,

I began using the olc engine few days ago and i'm not very familiar to it yet. I fallowed the tutorial video about the raycast world extensions engine, I've successfully reproduced what was showed in the tutorial but I'm facing some difficulties to implement some sprite animation. 

I tried implementing a function with <thread> and <chrono> preprocessors that return a value that with some conditions should draw the correct sprite at each frame, though it compiled the program crashed when I launched it. I think I don't understand how sprite rendering is done and I may have created an infinite loop. I've looked up the wiki section about time and didn't understand much how I could use that information to draw sprite animation in the raycast engine. So what function should I call in my rendering function in order to animate my sprite ? 

If you want to see which is the part of the code I'm talking about here's the example code inside "olc::Pixel SelectObjectPixel" that permits to draw a sprite from a sprite sheet:

`olc::Pixel SelectObjectPixel(const uint32_t id, const float sample_x, const float sample_y, const float distance, const float angle) 
	{
	olc::Pixel p = olc::MAGENTA;

	if(id == 1)
	{
    olc::vf2d vOffset;
		vOffset = { 4.0f, 0.0f };
    olc::vf2d vSample = ((vOffset + olc::vf2d(sample_x, sample_y)) * 64.87f) / olc::vf2d(float(gfxGuard.Sprite()->width),  float(gfxGuard.Sprite()->height));
	p = gfxGuard.Sprite()->Sample(vSample.x, vSample.y);
	}

 return p;
}`

Also in order to run the correct animation when needed who could I share a state of an object(running, firing ect...) to the rendring function ? Should I had to the object a parameter to define it's state and then adding this parameter to "olc::PixelSelectObjectPixel". Sorry If those questions are silly but I'm not knowing the engine well and the same goes for C++ that I haven't used much.

**Comment by matt-hayward** [comment]
I think it's difficult to debug without seeing some of _your_ code. However, I made a PGEX specifically for animating sprites, which may be just what you're looking for: https://github.com/matt-hayward/olcPGEX_AnimatedSprite

**Comment by lysergik** [comment]
So here is what I wanted to implement:

`int loopSprite(int a, int frames, int time){

    auto when_started = clock_type::now(); 

    auto target_time = when_started + (time*1ms);

        std::this_thread::sleep_until(target_time);

        target_time += (time*1ms);

        if(a != frames){
        a = a + 1;
            }

        if(a == frames) {
            a = 0;
                }
        auto now = clock_type::now();
     
    return a;}`

`
olc::Pixel SelectObjectPixel(const uint32_t id, const float sample_x, const float sample_y, const float distance, const float angle) {
		int a = 0;

	olc::Pixel p = olc::MAGENTA;


	if(id == 1)
	{

    a = loopSprite(a, 4, 50);
    olc::vf2d vOffset;
		 if(a == 1) vOffset = { 4.0f, 0.0f };
		 if(a == 2) vOffset = { 3.0f, 0.0f };
		 if(a == 3) vOffset = { 2.0f, 0.0f };

    olc::vf2d vSample = ((vOffset + olc::vf2d(sample_x, sample_y)) * 64.87f) / olc::vf2d(float(gfxGuard.Sprite()->width), float(gfxGuard.Sprite()->height));
	p = gfxGuard.Sprite()->Sample(vSample.x, vSample.y);
	}
 return p;}`

It's probably a barbaric method but I didn't how I could implement this. I've seen in many function the use of fElapsedTime which is probably more appropriate but I don't know how to use it properly. I looked at your extension it seems interesting but it doesn't seem to fit with the method used in the video and I don't understand in the example code if the sprite animation is link to an object or not. If not it's problematic because it isn't linked to the object movements, it does not collide to the border and I'm not sure that we could apply the method described in the video that permits to show different sprite on each angle of the sprite that give the 3d'ish illusion. That being said I'm maybe wrong.
