### ISSUE TITLE
Panning the universe freezes.

### ISSUE THREAD

**Issue by lolaswift** [OneLoneCoder/olcPixelGameEngine#191]
I was testing https://github.com/OneLoneCoder/olcPixelGameEngine/blob/master/Videos/OneLoneCoder_PGE_ProcGen_Universe.cpp
with Visual Studio 2019.
W, A, S and D keys to pan freezes sometimes:
1. Run the file, start from pressing W, it moves up a tiny bit then the program freezes.
2. Run the file,  Start from pressing S, it moves down with no issues and then press W, it moves up with no issues. However, when pressing A or D to pan left or right, the program freezes.
2. Run the file, Start from press A or D, panning left and right has no issues but W and S freezes.
I'm a beginner. I use Visual Studio 2019. No errors, no warnings.  Could you please help? thx.

**Comment by lolaswift** [comment]
Tried a few times. Looks like as long as I started using the W key to pan.  It caused the panning to freeze randomly on panning other directions.

**Comment by OneLoneCoder** [comment]
As a matter of policy, from now I will direct all none-PGE or PGEX related issues to the discord server: https://discord.gg/WhwHUMV
