### ISSUE TITLE
Console Window visible

### ISSUE THREAD

**Issue by sleimanzublidi** [OneLoneCoder/olcPixelGameEngine#192]
Hi, thank you for this code and the videos, they're an very easy way to get into the world of game engines.

I'm running my game in a Windows Console project and the console window is always present behind the game window. Is a little a annoying and people who tried the game keep closing it intuitively since is just some blank window. Is there any way to hide it on launch?

**Comment by OneLoneCoder** [comment]
Sure, change your project from a console one to a Windows one. Change main() to the winmain() prototype.

**Comment by sleimanzublidi** [comment]
Awesome!  To be clear this is what I changed:

Project Properties: Linker -> System -> SubSystem -> (/SUBSYSTEM:WINDOWS)

Replaced main() with:

```
int APIENTRY wWinMain(_In_ HINSTANCE hInstance,
	_In_opt_ HINSTANCE hPrevInstance,
	_In_ LPWSTR    lpCmdLine,
	_In_ int       nCmdShow)
{
	UNREFERENCED_PARAMETER(hPrevInstance);
	UNREFERENCED_PARAMETER(lpCmdLine);

	Game game;
	if (game.Construct(480, 320, 2, 2))
		game.Start();

	return 0;
}
```

**Comment by ozayturay** [comment]
Actually there is an easier solution still using main() as an entry point.

In the project build linker options set

```
/SUBSYSTEM:windows
/ENTRY:mainCRTStartup
```

Or use the following #pragma in the source file with the int main(...)

```
#pragma comment(linker, "/SUBSYSTEM:windows /ENTRY:mainCRTStartup")
```
