### ISSUE TITLE
A project regarding the creation of a GUI framework

### ISSUE THREAD

**Issue by AnonAmazing** [OneLoneCoder/olcPixelGameEngine#199]
@OneLoneCoder 

Hello,

I'm planning on creating a GUI Framework something similar to wxWidgets. I'm gonna be using olcPixelGameEngine to render it. I was also hoping if this could be a brother project of olcPixelGameEngine since I'm gonna be `#include` -ing it. It will have the following things (plan as of today):

- It will contain widgets like buttons, lists, textboxes.
- It will have events such as OnClick for a button.
- Easy to use.
- Simply coded header file. No very complex things that most beginners won't understand.

I am only bringing this to your attention @OneLoneCoder because maybe you're interested and want to contribute or do something for it. I'm still gonna be doing this even if you don't respond to this or like this idea.

From,
Clyde

**Comment by OneLoneCoder** [comment]
Hi Clyde, I've no issues with people creating PGE extensions, just be aware specifically with GUI ones there are already quite a few, and mine will be released shortly too, so there maybe some competition 😄

**Comment by AnonAmazing** [comment]
😂
Maybe mine will be like aiming for beginners. The users can possibly edit the header file so that it can match what the users want. Let's just call it a friendly competition or participation if you would like to call it that. Is there any way that I can contact you sir @OneLoneCoder? it will help.
