### ISSUE TITLE
Pressing left or right shift sets other key codes true

### ISSUE THREAD

**Issue by jakubshark** [OneLoneCoder/olcPixelGameEngine#2]
in the OnUserUpdate method I have a simple if statement 

if (GetKey(olc::Key::A).bHeld)
 doSomething();

when I press either of the shifts on my keyboard it sets it to true. this should only
be true when 'A' is being held.

**Comment by jakubshark** [comment]
Control also does the same thing

**Comment by OneLoneCoder** [comment]
Nice one, I was aware of ALT, I'll investigate this. Thanks!

**Comment by jakubshark** [comment]
I'm using Windows 10

**Comment by OneLoneCoder** [comment]
I'm just keeping this as a bit of a devlog, so no need to respond, I've identified the bug and fixed it for windows. I'll not upload a patch until I've tested it on linux tonight.

**Comment by OneLoneCoder** [comment]
Shift & Ctrl keys should function normally now. Keys that I have not provided any sensible definition for will still return as if A has been pressed, I know ALT will still do this, but if any others pop up that become inconvenient let me know. Requesting closed?
