### ISSUE TITLE
MMO Series bug: quick-fix for efficient monitoring

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [OneLoneCoder/olcPixelGameEngine#200]
https://github.com/OneLoneCoder/olcPixelGameEngine/blob/b27c89cc597ca24220475e6c35986d9836ddd23f/Videos/Networking/Parts1%262/net_tsqueue.h#L149-L153

should be the following code:

```cpp
std::unique_lock<std::mutex> ul(muxQueue);

while (deqQueue.empty())
{
    cvBlocking.wait(ul);
}
```
				
And everywhere in the netcode you are doing

```cpp
std::unique_lock<std::mutex> ul(muxBlocking);
cvBlocking.notify_one();
```

There should be no lock at all for the condition variable. This lock is doing nothing for correctness and just slowing things down.
What I mean is, it’s not wrong in the “violates invariants and/or deadlocks” context, it’s just not implementing a monitor efficiently. Locks are not expensive until they are and with an mmo, this will be an issue down the road.

**Comment by OneLoneCoder** [comment]
Taken under advisement.

-------
From now on: as a matter of policy, I will direct all none-PGE or PGEX related issues to the discord server: https://discord.gg/WhwHUMV
