### ISSUE TITLE
olcPGEX_DXR - Enabling DXR as part of the olcPGE

### ISSUE THREAD

**Issue by AnonAmazing** [OneLoneCoder/olcPixelGameEngine#203]
Hello again @OneLoneCoder,

If you remember, I'm the one who presented a project that is about a GUI extension to the olcPGE. I know that we have the ability to make extensions to this game engine, but here I go again asking for permission. After all asking permission is not bad. Here is my aim for the olcPGEX_DXR extension:

- Must be able to do raytracing using DX's DXR.
- Must be easy to understand.
- Must use the Windows way of doing GUI. Since, to my knowledge, you can only use DX if you use the Windows GUI library.

This is currently all the information that I can provide. I'm asking for your support @OneLoneCoder through contributions or any other way that you can help. My telegram username is @clydx12.

From your viewer and follower,
-Clyde

**Comment by OneLoneCoder** [comment]
Again, No issue with people making extensions - though Ive no plans on making a DirectX compatible renderer anytime soon. Other people have, though none have been fully up to spec, so not included in the release. Even if they do, I'm then reliant upon them keeping it up to date, so its unlikely DX renderer will be a major thing.

**Comment by AnonAmazing** [comment]
I'll try my best to make it amazing and easy to maintain. I also think that it is unlikely to be a major thing since it has a steep learning curve. But I'll do my best to make it easy to learning programmers, I'll do most of the hard work for them. I hope this DXR project becomes a part of this fantastic game engine of yours in the near future.

**Comment by AnonAmazing** [comment]
Instead of doing this, I'm going to create a GFX extension thing where I add more features to olcPGE. Features will probably include vertex shader for 2d and 3d convex shapes, rasterization, convex shape generation, and probably some functions to interact with the shapes drawn onto the screen like zoom in/out listener.
