### ISSUE TITLE
Sending string value from client to server

### ISSUE THREAD

**Issue by elena721** [OneLoneCoder/olcPixelGameEngine#204]
Hello OneLoneCoder!

I'm a beginner in C++. I practiced your videos and I tried to send a string value from client to server. 
Here is part of the code: 

Client: 
dfo::net::message<CustomMsgTypes> msg;
msg.header.id = CustomMsgTypes::ServerAskedForStringValue;
const char* myValue = "example";
msg << myValue;
Send(msg);  

Server:
char* myValue;
msg>>myValue;
dfo::net::message<CustomMsgTypes>responseMes;
responseMes.header.id = CustomMsgTypes::ServerMessage;
responseMes << "Value received";
client->Send(responseMes);

I received error when pull data out from message buffer: Access violation reading location.
Can you please help me with a hint to send the string value from client to server?

**Comment by OneLoneCoder** [comment]
Strings are a little trickier. Effectively you are just pushing a pointer into the message, which obviously wont do. Instead push the size of the string first, then the characters individually.

**Comment by maraneicu** [comment]
Thanks for your response! 
I managed to send the size of the string from client to server. Also I sent the characters of string individually from client to server. Problem is on server side when trying to pull out the data from message buffer. My code on server side is: 

std::string myValue;
for (int i = 0; i < msg.body.size(); i++)
{
	msg.body[i] >> myValue[i];
}

Also, tried with first character of string:

char firstCharacter;
msg.body[0] >> firstCharacter;

Can you please help me to pull data out from message buffer? I'm having troubles on working with strings.

**Comment by OneLoneCoder** [comment]
The opeartor[] overload on the vector msg.body will interfere with how the >> operator is working, so try just msg.body >> myValue[i].

----------
As a matter of policy, from now I will direct all none-PGE or PGEX related issues to the discord server: https://discord.gg/WhwHUMV
