### ISSUE TITLE
Filling a sprite with 0 alpha Pixels leads to them being black

### ISSUE THREAD

**Issue by joshinils** [OneLoneCoder/olcPixelGameEngine#21]
if i have a newly created sprite, with the pixelmode set to `SetPixelMode(olc::Pixel::Mode::ALPHA);` it evaluates the alpha blend of the existing empty pixels and the inserted one to black.
the default construcor of Pixel with which the Sprite has been filled (0,0,0,255) and any Pixel value of (r,g,b,0)
will result in a black tone of (0,0,0,255).
this confused me as i expected to create an empty sprite which i then fill with an empty/transparent color. then i could add little things in the sprite which would float. 
but they would actually be atop of black.

to fix this i can set the `SetPixelMode(olc::Pixel::Mode::NORMAL);` and then fill the sprite with transparent Pixels, then reset the `SetPixelMode(olc::Pixel::Mode::ALPHA);` and insert my "floating" pieces.

**Comment by OneLoneCoder** [comment]
You can of course also olc::Sprite::Clear(olc::Pixel(r, g, b, a)) without concerning yourself with blending modes. Given that I anticipate the bulk of users of olc::Sprite will not be off screen rendering I will leave the construction profile of olc::Sprite as is.
