### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Croydon** [OneLoneCoder/olcPixelGameEngine#228]
The license seems to be almost a [BSD 3-Clause license](https://spdx.org/licenses/BSD-3-Clause.html).

But just almost, what is the motivation behind using a custom license? This creates all kinds of legal headaches for people who (have to) take this stuff really seriously. 🙈

**Comment by Moros1138** [comment]
Firstly, it's very good that you take licensing seriously.

Secondly, Javid explains his reasoning for his license [here](https://github.com/OneLoneCoder/olcPixelGameEngine/wiki/Licencing).

Hope that helps you.
