### ISSUE TITLE
olcPGEX_Graphics3D.h missing #include?

### ISSUE THREAD

**Issue by ssta** [OneLoneCoder/olcPixelGameEngine#23]
`olcPGEX_Graphics3D.h: In static member function ‘static void olc::GFX3D::ClearDepth()’:
olcPGEX_Graphics3D.h:953:84: error: ‘memset’ was not declared in this scope
   memset(m_DepthBuffer, 0, pge->ScreenWidth() * pge->ScreenHeight() * sizeof(float));
`
This is solved by adding #include&lt;cstring&gt; to the file.  Not sure if this is a Linux specific thing or not?  I almost never do anything C/C++ any more, and never in Windows :)

**Comment by OneLoneCoder** [comment]
Hi ssta, I'll ask some of the linux users on the discord about this, but it does seem more of a build configuration issue. Which compiler are you using?
