### ISSUE TITLE
Mouse Methods always return 0

### ISSUE THREAD

**Issue by hamolicious** [OneLoneCoder/olcPixelGameEngine#231]
*PS - I will be linking full code later, I need to wait for confirmation from an artist on using their art*

Here is the snippet of code, it lives inside the `OnUserUpdate()` method
```c++
const olc::vi2d vMousePos = GetMousePos();
bool bRighMousePress = GetMouse(0).bHeld;
std::cout << GetMousePos() << ", " << " | " << bRighMousePress << std::endl;
```

However, the print method always shows me:
```
(0,0),  | 0
```
No matter where the mouse is, if it is being clicked or not.

**Comment by mtkaalund** [comment]
I would think, it is because you are using a `const olc::vi2d vMousePos = GetMousePos()` when first run `GetMousePos()` returns 0,0.
You should either use `olc::vi2d vMousePos` or `static olc::vi2d vMousePos` if it is in `OnUserUpdate()`

**Comment by hamolicious** [comment]
Yes that was a mistake in pasting.
```c++
std::cout << GetMousePos() << std::endl;
std::cout << GetMouse(0).bHeld << std::endl;
```
This will also return the same thing, just zeros for both

**Comment by OneLoneCoder** [comment]
Without actual code, its impossible to see whats wrong - but I can assure you, mouse stuff works just fine. You can try it here: https://community.onelonecoder.com/members/javidx9/PGEX_GUI_LIVE/

**Comment by hamolicious** [comment]
Yes I understand, sorry, I am not able to post the code immediately but I will comment with the GitHub Repository link later on today.

**Comment by hamolicious** [comment]
Sorry to keep you waiting, here is the full code I am using
https://github.com/hamolicious/Chess

**Comment by mtkaalund** [comment]
So from what I can see, is that you inherent from the pixelgameengine in both your example class and your chessPiece class. You should only inherent from one.

Try removening `class chessPiece : public olc::PixelGameEngine` with `class chessPiece` or move all the override functions into `chessPiece` and change make the change in `int main`.

Sorry for the format, I am on mobile and with 3 hours of sleep, cheers

**Comment by Au-lit** [comment]
Side note, I really like how you are still using v2.08 @hamolicious.

**Comment by hamolicious** [comment]
> So from what I can see, is that you inherent from the pixelgameengine in both your example class and your chessPiece class. You should only inherent from one.
> 
> Try removening `class chessPiece : public olc::PixelGameEngine` with `class chessPiece` or move all the override functions into `chessPiece` and change make the change in `int main`.
> 
> Sorry for the format, I am on mobile and with 3 hours of sleep, cheers

Now I just feel stupid, removing the inheritance from the `ChessPiece` class has fixed the issues!
Thank you so much to everyone.
