### ISSUE TITLE
the boundary-Pixels of Sprite::Sample and `Sprite::SampleBL` are computed wrong

### ISSUE THREAD

**Issue by joshinils** [OneLoneCoder/olcPixelGameEngine#24]
[`Sprite::Sample`](https://github.com/joshinils/olcPixelGameEngine/blob/1012b5e70b078a6ef149984c9388228e256d705c/olcPixelGameEngine.h#L841) can receive values for `x` and `y` which are 0 or 1 (or lower or higher)
this can result in the edges of a sprite being sampled out of bounds.
the change form 1.12 to 1.13 of shiftig by half a pixel has fixed the edge case of value 1, but shifted the whole sprite by half a pixel:

left 1.13, right my proposed solution:
![pgesamplewrong](https://user-images.githubusercontent.com/34302971/52192781-1109ef00-284c-11e9-95ab-e253ba49986e.png)

as for [`Sprite::SampleBL`](https://github.com/joshinils/olcPixelGameEngine/blob/1012b5e70b078a6ef149984c9388228e256d705c/olcPixelGameEngine.h#L850) the problem is about the same, but the initial u and v are being rounded in the wrong direction for very small values of u and v. if u and v are negative the cast rounds up to zero. explicitly using floorfixes the issues shown below.
then the same usage of min and max will allow access to color-values out of bounds.

left 1.13, right my proposed solution:
![pgesampleblwrong](https://user-images.githubusercontent.com/34302971/52193002-36e3c380-284d-11e9-898d-17c8ebc19513.png)

the image shown is always the same of size 5x5 .

**Comment by OneLoneCoder** [comment]
Thanks Josh, Im implementing this, I'll credit you in the header of course!
