### ISSUE TITLE
181 errors

### ISSUE THREAD

**Issue by CodeDiseaseDev** [OneLoneCoder/olcPixelGameEngine#249]
when i put the olcPixelGameEngine.h in my project
it said there were 181 errors in the header file... no idea why... but i thought i should make an issue about it
![image](https://user-images.githubusercontent.com/70626250/125066715-aa611d80-e0f6-11eb-955c-0a37666ce34a.png)

**Comment by matt-hayward** [comment]
Can you provide some further details about what you're doing? It's difficult to help without further context.

**Comment by CodeDiseaseDev** [comment]
im trying to make a basic tictactoe game in c++
but all you really need to know is that there is 181 errors in the `olcPixelGameEngine.h` file and i cant build my project with it

**Comment by matt-hayward** [comment]
Can you share some code to help identify the problem? The header file is well-used and most people don't have any problems.

**Comment by CodeDiseaseDev** [comment]
![image](https://user-images.githubusercontent.com/70626250/125067732-fa8caf80-e0f7-11eb-93c3-ae9dc4f2e71b.png)
mate
the problem is 181 syntax errors in the code

**Comment by matt-hayward** [comment]
Can you compile and run the example program found in the header file itself?

**Comment by CodeDiseaseDev** [comment]
dont worry i will just go without olcPixelGameEngine
