### ISSUE TITLE
Mouse location is not reported correctly on resized windows in X11

### ISSUE THREAD

**Issue by tpseitz** [OneLoneCoder/olcPixelGameEngine#25]
Mouse location is not reported correctly on resized windows in X11. This can be fixed with replacing line 1689:
```olc_UpdateMouse(xev.xmotion.x, xev.xmotion.y);```
with:
> XWindowAttributes gwa;
> XGetWindowAttributes(olc_Display, xev.xmotion.window, &gwa);
> olc_UpdateMouse(
>   (xev.xmotion.x * nScreenWidth * nPixelWidth) / gwa.width,
>   (xev.xmotion.y * nScreenHeight * nPixelHeight) / gwa.height);

**Comment by OneLoneCoder** [comment]
This is an ongoing debate, as I have consciously made the decision to not support window resizing. However perhaps a specific configuration flag can be added to enable this functionality. Thanks again!
