### ISSUE TITLE
net_tsqueue.h

### ISSUE THREAD

**Issue by anasouardini** [OneLoneCoder/olcPixelGameEngine#258]
all lines containe : std::scoped_lock lock(muxQueue);

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2760	syntax error: unexpected token 'identifier', expected ';'

networking\NetCommon\net_tsqueue.h	21

**Comment by anasouardini** [comment]
> 
> 
> all lines containe : std::scoped_lock lock(muxQueue);
> 
> Severity Code Description Project File Line Suppression State
> Error C2760 syntax error: unexpected token 'identifier', expected ';'
> 
> networking\NetCommon\net_tsqueue.h 21


when adding a typename : typename std::scoped_lock lock(muxQueue);

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'scoped_lock': is not a member of 'std'

networking\NetCommon\net_tsqueue.h	21

**Comment by OneLoneCoder** [comment]
Enable C++17 for your compiler

**Comment by anasouardini** [comment]
> Enable C++17

thank you soo much for the quick response, i changed from 14 to 17 and it wokred right away.
