### ISSUE TITLE
Any unmapped key is interpreted as key A

### ISSUE THREAD

**Issue by tpseitz** [OneLoneCoder/olcPixelGameEngine#26]
When user presses alt key in PGE application the key press is mapped as `olc::Key::A`. This seems to be caused by behaviour of map data structure in standard library. The documentation of `std::map::operator[]` says "If k does not match the key of any element in the container, the function inserts a new element with that key and returns a reference to its mapped value." In this case the value is the value seems to be the first element of `enum olc::Key`, which is `A`.

This problem could be solved with starting `olc::Key` with not used element ie. `NONE`.

This bug is also case of the issue #2

**Comment by OneLoneCoder** [comment]
OK tpseitz, a nice solution.
