### ISSUE TITLE
Unable to build/run program

### ISSUE THREAD

**Issue by CMSuisse** [OneLoneCoder/olcPixelGameEngine#275]
I always encounter the following error message when trying to build a program (with the olcPixelGameEngine.h file) with the command
g++ -o olcExampleProgram olcExampleProgram.cpp -lX11 -lGL -lpthread -lpng -lstdc++fs

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lX11
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lGL
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpng
collect2.exe: error: ld returned 1 exit status

This is quite confusing to me, because I have used Ubuntu to install the libpng-dev, the libx11-dev and the libglu1-mesa-dev librarys, as well as the ubuntu build essentials. I currently don't have any idea what to do now.

Building any other cpp file works just fine.

Btw, when I try to build using  the "Run Build Task" Option in the "Terminal" menu, I encounter the error log that I attached
[Error log VSCode.txt](https://github.com/OneLoneCoder/olcPixelGameEngine/files/8103768/Error.log.VSCode.txt)

**Comment by OneLoneCoder** [comment]
From what you've posted I cant tell what combination of OS, compiler, libraries, platforms or targets you are trying to build for. It looks like you are on windows, using mingw, but using the linux g++ compile command - Ive not figured out how ubuntu fits into this.

**Comment by CMSuisse** [comment]
Yeah, I'm also a bit confused as to what I did. Basically, all Google searches that I performed said, that I should use Ubuntu. Turns out, that you can use Ubuntu on Windows (I'm running a Windows 10 OS) when entering the command wsl --install in an admin-powershell terminal. But that patched together mess probably isn't working as intended.

**Comment by OneLoneCoder** [comment]
It isnt. Forget using a linux OS inside your windows OS for a moment - thats a distraction. Instead choose a windows compiler. I would recommend just downloading and installing Visual Studio since its free and feature rich, though you can stick with mingw if you wish. The ony problem with mingw is there are many fragmented versions of it - So I suggest using the MSYS2 flavour of it. Once youve got that setup, you'll need to follow the mingw specific instructions in the header file.

**Comment by CMSuisse** [comment]
Ok, so... I have installed Mingw and configured MSYS2 and have also donwloaded all librarys that MSYS2 recommends for development using "pacaman -S development" which downloaded all the librarys without an error. But I still get the error log that I have attached in the first comment when building the file.

**Comment by OneLoneCoder** [comment]
are you linking against windows or linux libraries? user32 gdi32 opengl32 gdiplus Shlwapi dwmapi stdc++fs note how these are not the same as th elinux equivalents

**Comment by CMSuisse** [comment]
I'm sorry, but I don't quite understand the question.

**Comment by Moros1138** [comment]
you're trying to use the linux build command on a windows machine, is the thousand foot overview of the situation.

```
g++ -o myProgram.exe myProgram.cpp -luser32 -lgdi32 -lopengl32 -lgdiplus -lShlwapi -ldwmapi -lstdc++fs -static -std=c++17
```

**Comment by CMSuisse** [comment]
It worked. It finally fricking worked. Thanks a lot for your help.
