### ISSUE TITLE
TransformedView::DrawLine uses wrong point in overloaded method

### ISSUE THREAD

**Issue by CrazyDaisyRecords** [OneLoneCoder/olcPixelGameEngine#277]
## Issue / Proposal
The overloaded method
``` cpp
void TransformedView::DrawLine(float x1, float y1, float x2, float y2, olc::Pixel p, uint32_t pattern)
```

uses `y2` instead of `y1` on start point:
``` cpp
DrawLine({ x1, y2 }, { x2, y2 }, p, pattern);
```

instead of
``` cpp
DrawLine({ x1, y1 }, { x2, y2 }, p, pattern);
```

**Comment by OneLoneCoder** [comment]
Excellent, Thanks, Fixed.

**Comment by CrazyDaisyRecords** [comment]
I have learned so much from your inspiring and entertaining videos. It‘s an honor to give something (even very little :) ) back. 

Keep on rocking!

Best regards, Christian
