### ISSUE TITLE
DrawRotatedDecal Pixel break

### ISSUE THREAD

**Issue by IcyChills** [OneLoneCoder/olcPixelGameEngine#284]
I noticed while using a spinning circle png image with DrawRotatedDecal that it causes pixel edge breaking while rotating.
I'm not sure if I'm missing a step to avoid this effect.

Same example code from the olc::PixelGameEngine 2.0 video on YT.

The result:
![pixelbreak](https://user-images.githubusercontent.com/72191422/166433235-1366e72a-4e3a-4349-a67f-7cf58abab3dd.PNG)

Sprite image:
![spin](https://user-images.githubusercontent.com/72191422/166433186-19b34e77-f1cb-4421-8363-6fe12d58cf6a.png)

**Comment by OneLoneCoder** [comment]
Since it's a pixelated image it is aliasing to PGE pixels. You could perhaps filter the image. When you load it, one of the arguments is "filter", set it to true.

**Comment by IcyChills** [comment]
> Since it's a pixelated image it is aliasing to PGE pixels. You could perhaps filter the image. When you load it, one of the arguments is "filter", set it to true.

Thank you, I did not look at the arguments for Decal. It is fixed now. Also thank you and to the contributors for this engine. It great.

Closing as this issue has been resolved. User error on my part.
