### ISSUE TITLE
olc::Sprite::loader.Mypair._Myval2 was nullptr

### ISSUE THREAD

**Issue by Jordaber** [OneLoneCoder/olcPixelGameEngine#287]
Hi, this is my first time using github so I apologise if I am doing something wrong here.

I am working on a project and am trying to draw sprites on a 10 x 10 grid. The tiles are stored in a map with a tuple<int,int> key representing the tile coordinate. When initialising the map, each tile is created as a default tile object.  

`
sprite = new olc::Sprite(texture);
`

sprite is a olc::sprite pointer
and texture is a string containing the sprite texture location. For the case of the default tile object it is "default.png"

For some reason this line of code throws an exception: "**olc::Sprite::loader._Mypair._Myval2 was nullptr.**" at **olc::rcode Sprite::LoadFromFile().**

I am using visual studio 2019

I am not quite sure of the issue here. I've traced it back to OLC_IMAGE_GDI being defined.

**Comment by OneLoneCoder** [comment]
Let's see some code then!

**Comment by Jordaber** [comment]
Okay, I feel a bit silly for this but I found the cause of the problem. I will post my code here in case anyone else has the same issue.

This function is called **once** from main before anything else. Including before the olc::PixelGameEngine object is created.

```
std::map<std::tuple<int,int>, tile*> map;
std::vector<std::thread> threadList;

void setup() {
	//Populate map with tile objects
	int x = 0;
	int y = 0;
	for (int i = 0; i < 100; i++) {
		map[{x,y}] = new tile(&map,x,y);
		x++;
		if (x%10==0) {
			x = 0;
			y++;
		}
	}

	//Start tile event threads
	std::map<std::tuple<int, int>, tile*>::iterator it;
	for (it = map.begin(); it != map.end(); it++) {
		if (it->second->hasUpdate) {
			std::cout << "Starting " << it->second->name << std::endl;
			threadList.push_back(it->second->updateThreadCaller());
		}
	}
}
```

The constructor for tile is the following:

```
tile::tile(std::map<std::tuple<int, int>, tile*>* mapPtr, int xx, int yy) {
	sprite = new olc::Sprite(texture);
	x = xx;
	y = yy;
	map = mapPtr;
}
```

The issue occurs when the first line of the constructor is called. Throwing the error "olc::Sprite::loader._Mypair._Myval2 was nullptr."

I realise that this issue does not occur when the code within the setup function is placed within OnUserCreate(). It also works if the setup() function is called after olc::PixelGameEngine is created. 
Really a silly mistake on my part.
