### ISSUE TITLE
'olc::Sprite::Sprite(const olc::Sprite &)': attempting to reference a deleted function

### ISSUE THREAD

**Issue by Kotambail-Hegde** [OneLoneCoder/olcPixelGameEngine#294]
The below code snippet is causing the issue
	class Sprite
	{
	public:
		Sprite();
		Sprite(const std::string& sImageFile, olc::ResourcePack* pack = nullptr);
		Sprite(int32_t w, int32_t h);
		Sprite(const olc::Sprite&) = **delete**;
		~Sprite();

and the issue gets resolved, if the snippet is modified to
	class Sprite
	{
	public:
		Sprite();
		Sprite(const std::string& sImageFile, olc::ResourcePack* pack = nullptr);
		Sprite(int32_t w, int32_t h);
		Sprite(const olc::Sprite&) = **default**;
		~Sprite();

**Comment by Moros1138** [comment]
I believe this is a deliberate design choice by javid

A quote from javid himself, in response to a similar inquiry/request on the discord server

```
To deliberately discourage the copying of sprites
If you're copying sprites without thought, you've a significant design flaw
```

**Comment by Joseph21-6147** [comment]
@Kotambail-Hegde I ran into this same issue when following the NES tutorial by Javidx9. Here's the notes of how you might deal with this situation. Mabye of use for you:

[NES and PGE compatibility - olcSprite vars to pointers.pdf](https://github.com/OneLoneCoder/olcPixelGameEngine/files/9307299/NES.and.PGE.compatibility.-.olcSprite.vars.to.pointers.pdf)

**Comment by Kotambail-Hegde** [comment]
Got it. Will look into "Duplicate" instead of using the Copy Constructor. I will close the issue since the design is intentional. 
Thanks
