### ISSUE TITLE
Memory leaks for olc::Sprite

### ISSUE THREAD

**Issue by maksym33** [OneLoneCoder/olcPixelGameEngine#33]
Hi,
firstly I wanted to thank you for your code.
I was using the main thing (OlcPixelEngine) and encountered some memory leaks with valgrind, I think the issue is in this line:
`669  	if (pColData) delete pColData;`
I think changing it to
`669  	if (pColData) delete[] pColData;`
would fix it.

Additionally, there are some other memory leaks in Sprite::LoadFromFile(), mainly in lines:
`768          png = png_create_read_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);`
`771		info = png_create_info_struct(png); `
`805		row_pointers = (png_bytep*)malloc(sizeof(png_bytep) * height);`

After some time, I found that adding
`for (int y = 0; y < height; y++)`
`      free(row_pointers[y]);`
`free (row_pointers);`
`png_destroy_read_struct(&png, &info, png_infopp_NULL);`
at the ned of the LoadFromFIle() function fixes the final three leaks.

Regards,
Maks

**Comment by OneLoneCoder** [comment]
Thanks maksym, I'll address these in next update.
Jx9

**Comment by OneLoneCoder** [comment]
Not forgotten, gonna look at the png stuff now

**Comment by maksym33** [comment]
Cheers.
I don't think it's a huge memory leak - it only becomes apparent when you
run several thousands of games. I used your engine to visualize the results
of training a neural network (DQN algorithm) that controls a character in
2D platformer game I created. Like I said, after training for several
thousand games it crashed due to this leak.
Cheers,
Maks

**Comment by mrennix** [comment]
The pColData bug is still there in 1.24, line 752.

`Sprite::~Sprite()
	{
		if (pColData) delete pColData;
	}
`

**Comment by OneLoneCoder** [comment]
OK, All of these fixes are in next major version. Thanks all! Closing.
