### ISSUE TITLE
Missing assets/MegaSprite1.png

### ISSUE THREAD

**Issue by brccabral** [OneLoneCoder/olcPixelGameEngine#334]
Hi,
I was able to compile the `examples`, but for `TEST_Animate2D.cpp` it is needed file `./assets/MegaSprite1.png` which is not in project.
Can you add MegaSprite1.png into project?
Thank you

**Comment by OneLoneCoder** [comment]
It's not my asset to distribute unfortunately. The example provides sufficient info to be adapted to work with your own assets.

**Comment by brccabral** [comment]
I created this image so I could test, if you want to use it go ahead.

![image](https://user-images.githubusercontent.com/130455/234077952-f52ffdec-bf41-4f3c-944e-c5bd9f844c0e.png)
