### ISSUE TITLE
Idea: Can we add a curated list of PGE Showcase projects into the Repo

### ISSUE THREAD

**Issue by gurkanctn** [OneLoneCoder/olcPixelGameEngine#35]
There are many users out there who enjoy coding stuff using the PGE.

How about creating a curated list of PGE projects that various users have created, links to GitHub repo's, or links to YouTube or other videos?

I can understand that this might be a bit dangerous, to moderate and to keep things secure/safe for the public. But still, I think this can be considered by @OneLoneCoder as a reach-out for those of us who do not have many options to enlist their creations.

**Comment by OneLoneCoder** [comment]
Hi, This is a great idea, and is something I am currently implementing as I redevelop the OneLoneCoder.com website. I do have a contributors folder with links to other bits and pieces but you're right a showcase folder with links to projects is excellent.

This will be happening shortly.

Thanks buddy!
Jx9
