### ISSUE TITLE
Directly draw on a sprite --> scaled string

### ISSUE THREAD

**Issue by TuxxuT** [OneLoneCoder/olcPixelGameEngine#353]
I'm currently working on a board game and of course I have to draw the individual playing fields adequately.
For me, each playing field is a sprite that I place n times on the main window.
I don't use graphic files such as PNGs for the sprites, but create the sprites dynamically at runtime.

I think it will be clearer if I show the example source code...
```
bool OnUserCreate() override
{
// build up some sprites manually (drawing on the sprite "canvas", not per file load)
sprTile = std::make_unique<olc::Sprite>(32, 32);
SetDrawTarget(sprTile.get()); // enter: draw on the sprite
DrawLine(olc::vi2d(0, 0), olc::vi2d(sprTile.get()->Size().x, sprTile.get()->Size().y), olc::WHITE);
DrawLine(olc::vi2d(sprTile.get()->Size().x, 0), olc::vi2d(0, sprTile.get()->Size().y), olc::WHITE);
DrawStringProp(olc::vi2d(2, 12), "S", olc::WHITE, 1);
DrawStringProp(olc::vi2d(24, 12), "S", olc::WHITE, 1);
// create Decal for the Sprite
decalForMySprite = std::make_unique<olc::Decal>(sprTile.get());
SetDrawTarget(nullptr); // exit: draw on the sprite
}

bool OnUserUpdate(float fElapsedTime) override
{
     // Erase previous frame
     Clear(olc::BLACK);

fAngle += 4.0f * fElapsedTime;

     // place a sprite
     DrawSprite(olc::vi2d(ScreenWidth() / 2 - (sprTile.get()->Size().x / 2), ScreenHeight() / 2 - (sprTile.get()->Size().y / 2)), sprTile.get());

     // test rotated sprite
     DrawRotatedDecal(olc::vi2d(30, 30), decalForMySprite.get(), fAngle, { 16,16 }, { 1,1 });
}
        

```
This all works very, very well. However, I have a problem with the labels or the strings. The letters are currently much too big and I would have to be able to draw them scaled in the Sprite-Area (sprTile)...
But somehow that doesn't work at the moment.

I also tried the DrawStringDecal() method, where you can specify a scaling factor. Unfortunately, no letter is drawn in the sprite area here.

```
//DrawStringProp(olc::vi2d(2, 12), "S", olc::WHITE, 1);
DrawStringDecal(olc::vi2d(2, 12), "S", olc::WHITE, olc::vf2d{ 0.3, 0.3 });
DrawStringProp(olc::vi2d(24, 12), "S", olc::WHITE, 1);
```

What is the solution here?
Thank you very much!

**Comment by OneLoneCoder** [comment]
So two things to keep in mind, you can't draw decals to sprites, and you can't scale down text when drawing as a sprite. Given your other constraints, then an option would be to scale your playing field up so the font looks sensible, and then draw the playing field as a decal so you can scale it back down. Keep in mind that the font is about as small as single pixels allow, so perhaps your overall application resolution is too low for what you need.

**Comment by TuxxuT** [comment]
@OneLoneCoder
Thank you very much for the quick help and the useful information. 
Now I'll just draw the field larger so that everything fits the font size. Later it will be treated as a decal with a scaling factor of 0.5. The playing field is then the correct size, still looks good and the labeling is easy to read.
Problem solved. Thank you very much!
