### ISSUE TITLE
UTF16-LE encoded source file (intepreted as "binary")

### ISSUE THREAD

**Issue by WSSDude** [OneLoneCoder/olcPixelGameEngine#38]
The file in question is recently added `OneLoneCoder_PGE_olcEngine3D.cpp`. 
I think you accidentally saved it with UTF16-LE encoding, as all other files seems to be in UTF8. This single file is being interpreted as binary file on GitHub (if you try to open it... even in commit it came with it is being shown that way).

**Comment by ThePiGuy24** [comment]
I can also confirm this, it prevents g++ from compiling it.

**Comment by OneLoneCoder** [comment]
Understood, I'm a supporter of UTF-8 everywhere :D, and my toolchain is now configured that way too.
