### ISSUE TITLE
PixelGameEngine::Construct() not defined for Ubuntu

### ISSUE THREAD

**Issue by vbl10** [OneLoneCoder/olcPixelGameEngine#384]
Tried to run the example program and did not build. It seems PixelGameEngine::Construct() definition is disabled by an #ifdef somewhere

**Comment by Moros1138** [comment]
There is a macro that tells the compiler to include the implementations of all of the PGE stuff. 

```#define OLC_PGE_APPLICATION```

In a single file project (like the example program), this is required before you include the PGE header file.

If doing this doesn't solve the problem for you, then I'll need more information.

* Compiler/Toolchain being used.
* The command you used to compile the program. Including all of the flags you used.
* The compiler output, including the **full error message**.
* and any other information you think is pertinent.

**Comment by vbl10** [comment]
That worked. Thanks!
