### ISSUE TITLE
Specify max refresh rate/fps

### ISSUE THREAD

**Issue by srad** [OneLoneCoder/olcPixelGameEngine#41]
Can there be an option to define the maximum refresh rate?
Doesn't really make sense to have thousands of frames performance wise.

**Comment by calumpwebb** [comment]
Hey not sure if relevant anymore but you could modify the header file to do the following:

https://stackoverflow.com/questions/38730273/how-to-limit-fps-in-a-loop-with-c

**Comment by OneLoneCoder** [comment]
You now have the option to v_sync in Construct() function, if you need lower still then go with accumulating fElapsedTime until period is satisfied.
