### ISSUE TITLE
Incorrect rendering using OpenGL

### ISSUE THREAD

**Issue by stegus64** [OneLoneCoder/olcPixelGameEngine#49]
On my machine the OpenGL viewport does not work properly. It might be a bug in my very old version of Windows (2015 LTSB or Version 10.0.10240)

![image](https://user-images.githubusercontent.com/51655419/69866209-c4444880-12a3-11ea-9d1b-b14344208eb7.png)

As you can see the top part of the viewport is rendered **under** the title bar.
I suspect the problem is caused by the dwm. It feels like OpenGL is rendering correctly but then the resulting viewport (that fits the client area) is stretched so it fills the entire window including the window borders. Very strange.

The only way I have found to get the olcPixelGameEngine to work properly on my machine is to not use OpenGL. DirectX works perfectly.

This is the result of running the same code with DirectX:

![image](https://user-images.githubusercontent.com/51655419/69866431-52203380-12a4-11ea-8703-d0f9000d1e8d.png)

(I have added the red border and the diagonal line to debug this issue)

**Comment by UnusefulCoder** [comment]
Seems like OpenGL don't like borders... Have you tried to disable or move the contents down a bit?

**Comment by ishidex2** [comment]
try moving frame quad
