### ISSUE TITLE
ERROR: use of deleted function 'olc::ResourcePack::sEntry::sEntry(olc::ResourcePack::sEntry&&)'     auto streamBuffer = pack->GetStreamBuffer(sImageFile);

### ISSUE THREAD

**Issue by BaderEddineOuaich** [OneLoneCoder/olcPixelGameEngine#51]
Hi there, 
<strong>First thanks for the hard work that has been done to assemble this delicious game engine!</strong>
i got an issue after i changed my compiler from the visual studios to MinGW.
although it was working fine with the visual studio compiler (#undef "if it works, don't touch it")
not sure if i am doing something wrong here or there is a bug.
here are the details of this issue.
Thanks once again for the great work!!!
<pre>
OneLoneCoder Pixel Game Engine v1.20 
Windows10 64bit
Compiler:  MinGW64 3.4 | GDB 7.8.1
IDE: CLion 2019.2.3 64bit
</pre>
<pre>
====================[ Build | FlappyBird | Debug ]==============================
"C:\Program Files\JetBrains\CLion 2019.2.3\bin\cmake\win\bin\cmake.exe" --build C:\Users\bader\Desktop\FlappyBird\cmake-build-debug --target FlappyBird -- -j 1
[ 50%] Building CXX object CMakeFiles/FlappyBird.dir/main.cpp.obj
In file included from C:\Users\bader\Desktop\FlappyBird\main.cpp:2:0:
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h: In member function 'olc::rcode olc::Sprite::LoadFromPGESprFile(std::string, olc::ResourcePack*)':
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:745:56: error: use of deleted function 'olc::ResourcePack::sEntry::sEntry(olc::ResourcePack::sEntry&&)'
    auto streamBuffer = pack->GetStreamBuffer(sImageFile);
                                                        ^
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:341:10: note: 'olc::ResourcePack::sEntry::sEntry(olc::ResourcePack::sEntry&&)' is implicitly deleted because the default definition would be ill-formed:
   struct sEntry : public std::streambuf {
          ^
In file included from E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/ios:43:0,
                 from E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/ostream:38,
                 from E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/iostream:39,
                 from C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:224,
                 from C:\Users\bader\Desktop\FlappyBird\main.cpp:2:
E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/streambuf:802:7: error: 'std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]' is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from C:\Users\bader\Desktop\FlappyBird\main.cpp:2:0:
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:341:10: error: within this context
   struct sEntry : public std::streambuf {
          ^
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h: In member function 'olc::rcode olc::ResourcePack::AddToPack(std::string)':
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:980:19: error: use of deleted function 'olc::ResourcePack::sEntry& olc::ResourcePack::sEntry::operator=(const olc::ResourcePack::sEntry&)'
   mapFiles[sFile] = e;
                   ^
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:341:10: note: 'olc::ResourcePack::sEntry& olc::ResourcePack::sEntry::operator=(const olc::ResourcePack::sEntry&)' is implicitly deleted because the default definition would be ill-formed:
   struct sEntry : public std::streambuf {
          ^
In file included from E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/ios:43:0,
                 from E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/ostream:38,
                 from E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/iostream:39,
                 from C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:224,
                 from C:\Users\bader\Desktop\FlappyBird\main.cpp:2:
E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/streambuf:810:7: error: 'std::basic_streambuf<_CharT, _Traits>& std::basic_streambuf<_CharT, _Traits>::operator=(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]' is private
       operator=(const basic_streambuf&) { return *this; };
       ^
In file included from C:\Users\bader\Desktop\FlappyBird\main.cpp:2:0:
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:341:10: error: within this context
   struct sEntry : public std::streambuf {
          ^
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h: In member function 'olc::rcode olc::ResourcePack::LoadPack(std::string)':
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:1050:24: error: use of deleted function 'olc::ResourcePack::sEntry& olc::ResourcePack::sEntry::operator=(const olc::ResourcePack::sEntry&)'
    mapFiles[sFileName] = e;
                        ^
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h: In member function 'olc::ResourcePack::sEntry olc::ResourcePack::GetStreamBuffer(std::string)':
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:1068:24: error: use of deleted function 'olc::ResourcePack::sEntry::sEntry(const olc::ResourcePack::sEntry&)'
   return mapFiles[sFile];
                        ^
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:341:10: note: 'olc::ResourcePack::sEntry::sEntry(const olc::ResourcePack::sEntry&)' is implicitly deleted because the default definition would be ill-formed:
   struct sEntry : public std::streambuf {
          ^
In file included from E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/ios:43:0,
                 from E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/ostream:38,
                 from E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/iostream:39,
                 from C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:224,
                 from C:\Users\bader\Desktop\FlappyBird\main.cpp:2:
E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/streambuf:802:7: error: 'std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]' is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from C:\Users\bader\Desktop\FlappyBird\main.cpp:2:0:
C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:341:10: error: within this context
   struct sEntry : public std::streambuf {
          ^
In file included from C:\Users\bader\Desktop\FlappyBird\main.cpp:4:0:
C:\Users\bader\Desktop\FlappyBird\olcPGEX_Sound.h: In member function 'olc::rcode olc::SOUND::AudioSample::LoadFromFile(std::string, olc::ResourcePack*)':
C:\Users\bader\Desktop\FlappyBird\olcPGEX_Sound.h:297:68: error: use of deleted function 'olc::ResourcePack::sEntry::sEntry(olc::ResourcePack::sEntry&&)'
    olc::ResourcePack::sEntry entry = pack->GetStreamBuffer(sWavFile);
                                                                    ^
C:\Users\bader\Desktop\FlappyBird\olcPGEX_Sound.h: At global scope:
C:\Users\bader\Desktop\FlappyBird\olcPGEX_Sound.h:583:50: error: use of deleted function 'std::atomic<unsigned int>::atomic(const std::atomic<unsigned int>&)'
  std::atomic<unsigned int> SOUND::m_nBlockFree = 0;
                                                  ^
In file included from C:\Users\bader\Desktop\FlappyBird\olcPixelGameEngine.h:230:0,
                 from C:\Users\bader\Desktop\FlappyBird\main.cpp:2:
E:/Programs/DevC++/Tools/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/atomic:624:7: note: declared here
       atomic(const atomic&) = delete;
       ^
CMakeFiles\FlappyBird.dir\build.make:61: recipe for target 'CMakeFiles/FlappyBird.dir/main.cpp.obj' failed
mingw32-make.exe[3]: *** [CMakeFiles/FlappyBird.dir/main.cpp.obj] Error 1
CMakeFiles\Makefile2:74: recipe for target 'CMakeFiles/FlappyBird.dir/all' failed
mingw32-make.exe[2]: *** [CMakeFiles/FlappyBird.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles/FlappyBird.dir/rule] Error 2
CMakeFiles\Makefile2:81: recipe for target 'CMakeFiles/FlappyBird.dir/rule' failed
Makefile:117: recipe for target 'FlappyBird' failed
mingw32-make.exe: *** [FlappyBird] Error 2
</pre>

**Comment by OneLoneCoder** [comment]
Thanks, Im aware of this, its actually a bug in the sound extension - i'll roll out a fix this weekend. For now you can just comment out the offending section because it isnt used in normal applications anyway.

**Comment by BaderEddineOuaich** [comment]
Oh alright then. thanks 🙏
