### ISSUE TITLE
olcPGEX_Sound.h only works on x64, x86 crashes on waveOutOpen

### ISSUE THREAD

**Issue by westndesign** [OneLoneCoder/olcPixelGameEngine#52]
Issue 1: olcPGEX_Sound.h only works on x64, x86 crashes on waveOutOpen
Issue 2: olcPGEX_Sound.h in SavingSedit is 0.4 while the version in videos is 0.3.

**Comment by OneLoneCoder** [comment]
On the whole PGEX sound needs some attention, and i'll be having a major PGE release in a few weeks so i'll overhaul it then to make sure everything remains compatible.
