### ISSUE TITLE
Suggestion: saving to .png files.

### ISSUE THREAD

**Issue by ddddtttt6666** [OneLoneCoder/olcPixelGameEngine#53]
I had to use external library for saving images. would be super nice to have the ability of saving to .png straight from olcPixelGameEngine!

**Comment by OneLoneCoder** [comment]
While I agree its a "nice to have", on the whole it has little practical value but requires a significant addition to the linux code base. Perhaps if someone where to create an "imaging" extension then this feature would be a must.
