### ISSUE TITLE
Visual Studio doesn't update __cplusplus macro unless given a flag

### ISSUE THREAD

**Issue by ThePixelGamer** [OneLoneCoder/olcPixelGameEngine#54]
![image](https://user-images.githubusercontent.com/15077848/70857834-83f7e380-1ebb-11ea-8b09-44a7618ebe03.png)
![image](https://user-images.githubusercontent.com/15077848/70857836-89552e00-1ebb-11ea-8575-4292d030e58d.png)
![image](https://user-images.githubusercontent.com/15077848/70857846-aee23780-1ebb-11ea-8c0c-70cad1f5dc61.png)

https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/
I don't know if any of this is useful as it seems to work fine even when compiling with C++17 but I thought it should be brought up

**Comment by OneLoneCoder** [comment]
Yeah this is a tricky one. In my experiments and sigh... "on my machine" it works just fine, but I think MS rolled out this change in a patch for VS, so some people have it and others dont. I'll leave it here for others to see though.

**Comment by OneLoneCoder** [comment]
Hopefully resolved now.
