### ISSUE TITLE
Fonts are really big

### ISSUE THREAD

**Issue by pflannery** [OneLoneCoder/olcPixelGameEngine#6]
I was following your spline tutorial (good tutorial by the way) and found that the fonts are rendered much bigger that what the olcConsoleGameEngine outputs in your tutorial.

Example code

```cpp
using namespace std;

#include "olcPixelGameEngine.h"

class Example : public olc::PixelGameEngine
{
  public:
    Example()
    {
        sAppName = "Example";
    }

  public:
    bool OnUserCreate() override
    {
        // Called once at the start, so create things here
        return true;
    }

    bool OnUserUpdate(float fElapsedTime) override
    {
        float x = 80.f, y = 40.f;
        DrawRect(x - 1, y - 1, 2, 2);
        DrawString(x, y, to_string(3));
        return true;
    }
};

int main()
{
    Example demo;
    if (demo.Construct(160, 80, 10, 10))
        demo.Start();

    return 0;
}
```

Screenshot
![image](https://user-images.githubusercontent.com/1727302/45934603-20248a80-bf98-11e8-9c58-9bbaf1e4d4b0.png)

**Comment by OneLoneCoder** [comment]
Lol, yes...
Whereas the console treated characters like pixels, it could still treat characters like characters too. Unfortunately with the PixelGameEngine, the character is made up of pixels. I guess this is the fundamental difference between the two - though I dont make a claim that they are 100% interchangeable - anything with text is probably going to need some adjustment.

**Comment by pflannery** [comment]
ok enlarging the size of my rectangles seems to do the trick ;)

```cpp
DrawRect(x - 5, y - 5, 10, 10);
DrawString(x - 3, y - 3, to_string(0));
```
![image](https://user-images.githubusercontent.com/1727302/45988036-97c3e980-c06c-11e8-960e-85178f3ba809.png)
