### ISSUE TITLE
olcPixelGameEngine.h:1031:24: error: ‘_gfs’ has not been declared

### ISSUE THREAD

**Issue by Atx85** [OneLoneCoder/olcPixelGameEngine#60]
Hi, I'm quite a beginner, but maybe it's worth to mention that I have this issue:

$ g++-9 -g -Wall -o test olcExampleProgram.cpp -std=c++17 -lX11 -lGL -lpthread -lpng -lstdc++fs 
In file included from olcExampleProgram.cpp:2:
olcPixelGameEngine.h: In member function ‘bool olc::ResourcePack::AddFile(const string&)’:
olcPixelGameEngine.h:1028:7: error: ‘_gfs’ has not been declared
 1028 |   if (_gfs::exists(file))
      |       ^~~~
olcPixelGameEngine.h:1031:24: error: ‘_gfs’ has not been declared
 1031 |    e.nSize = (uint32_t)_gfs::file_size(file);

**Comment by tabris2015** [comment]
same error here, I think that somehow, the last commit broke something

**Comment by Atx85** [comment]
Awesome!!! Thanks!
