### ISSUE TITLE
Incorrect __linux__ macro

### ISSUE THREAD

**Issue by Cecilectomy** [OneLoneCoder/olcPixelGameEngine#62]
https://github.com/OneLoneCoder/olcPixelGameEngine/blob/7b232aba8b83eb2eb0b8afaf67cf0842b1c4b2cd/olcPixelGameEngine.h#L261

This should be \_\_linux\_\_ not \_linux\_
causes "error: ‘\_gfs’ has not been declared"

**Comment by OneLoneCoder** [comment]
Yeah, my bad, i'll fire my linux testers :D
