### ISSUE TITLE
Run on VS Code

### ISSUE THREAD

**Issue by AyushKool** [OneLoneCoder/olcPixelGameEngine#64]
I tried to run the example program in VS Code and it is giving me multiple errors. First, it gave the error:  <experimental/filesystem> no such file exists. I then tried commenting this part out and just leaving it as  <filesystem> and then the error subsided.

But then a new error popped: 
olcPixelGameEngine.h:1235:8:
   std::thread t = std::thread(&PixelGameEngine::EngineThread, this);
        ^~~~~~
olcPixelGameEngine.h:1248:3: error: 't' was not declared in this scope
   t.join();

**Comment by OneLoneCoder** [comment]
Can you show information which people can use to actually help you please? Such as compiler versions, OS, available packages, and how you actually go about building the code.

**Comment by AyushKool** [comment]
IDE: VS Code (using C/C++ extention and Code Runner)

OS: Windows 10 (64 bit)

Compiler: MinGW:
gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.


I even installed Visual Studio (with Desktop C++) and tried to run it on that and it is still giving me the same errors. First, it is giving an error in #include <experimental/filesystem> and when I resolve that by commenting it out then the error is the one with #inlcude thread which I mentioned above.

P.S. I checked and nothing is wrong with my compiler or path because the olcConsoleGameEngine.h is working fine. It is just not working for the olcPixelGameEngine.h for some reason.

**Comment by vegapit** [comment]
A fresh install of VS 2019 gets a filesystem error on compilation. To get rid of it, I just added the following line at the start of my `main.cpp` file:
```
#define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING
```
Would it be what you need?

**Comment by Billwilliams1952** [comment]
Adding the #define worked for me.
