### ISSUE TITLE
Actually, a question. Because I don't use Discord. About the RNG Universe.

### ISSUE THREAD

**Issue by TediusTimmy** [OneLoneCoder/olcPixelGameEngine#66]
Where did you get your Lehmer PRNG? It doesn't look like anything on the Wikipedia page you showed. It looks more sophisticated, with extra hardening of the results.

PS, when are you going to upload the NES part 6 code? Did you get a cease-and-desist from Nintendo? I was just taking the piss out of you about actually using git. Please don't tell me you tried and are now in a detached head state that you don't know how to reattach.

**Comment by ishidex2** [comment]
Math formulas usually look more complicated than the actual implementation

**Comment by TediusTimmy** [comment]
Wikipedia's definition of a Lehmer random number generator is of the form:
x(n+1) = a * x(n) mod m
Where you choose a and m such that the period of the sequence is m-1 (usually).

His implementation, however:
Takes the seed and adds a magic number. He then multiplies the result by another magic number, xors the high 32 bits onto the low 32 bits, multiplies this result by a third magic number, again xoring the high 32 bits onto the low 32 bits, and finally returns the low 32 bits.

So, you've got an additive sequence that feeds into two sequential Lehmer RNGs of modulus 2^32, where the output of each Lehmer is conditioned with the truncated bits (probably because a power of 2 is a poor modulus).

I don't know what algorithm it is, but it seems to be random enough for his uses. I was just wondering if he had a reference for it.
