### ISSUE TITLE
Possible problem with drawing drawing 3D obj files

### ISSUE THREAD

**Issue by slzatz** [OneLoneCoder/olcPixelGameEngine#69]
If you use teapot.obj from the Videos repository with olcPixelGameEngine.h and OneLoneCoder_PGE_olcEngine3d.cpp, things are generally working (which is very cool) but there do seem to be issues.  For example, the knob at the top of the lid is visible through the sides of the teapot as is the spout and the handles.  On the other hand, the bottom of the teapot behaves as expected and blocks the view of those parts of the teapot when they are behind it.  I am running this on Arch Linux with no changes to olcPixelGameEngine.h and none to the olcEngine3d.cpp (other than bypassing the texture code for these tests).  First of all, I was wondering if someone can confirm that they are seeing the same thing as I assume what I am seeing is not the desired behavior.  Thanks.

**Comment by OneLoneCoder** [comment]
This is possible depending on which code you run. In the first simple demo, the depth sorting is done on a per triangle center point depth basis. This is crude (and was there to indicate a point in part 4). The last version of the renderer uses a genuine depth buffer to remove such artifacts.

**Comment by slzatz** [comment]
I am using OneLoneCoder_PGE_olcEngine3d.cpp from the olcPixelGameEngine repository (this repository) and there is a depth buffer.

**Comment by slzatz** [comment]
I now see that the depth buffer only applies to the texture-related code and that if you uncomment the triangle sort code, objects without textures are rendered as expected.  It may make sense to have the depth buffer apply whether there is a texture or not but I'll close this issue.
