### ISSUE TITLE
Set custom mouse arrow 

### ISSUE THREAD

**Issue by semasdev** [OneLoneCoder/olcPixelGameEngine#70]
Hello,
not really a PixelEngine related problem, but i tried to set a custom cursor arrow in this function: 
```
LRESULT CALLBACK PixelGameEngine::olc_WindowEvent(HWND hWnd, UINT [...]) {
case WM_SETCURSOR: SetCursor(hCurs1);return 0; //created a custom cursor with CreateCursor()
}
```
which works quite well,  it shows my custom cursor arrow, but the cursor disappears after 30 seconds and stays invisible, mouse functions like dragging still work though.

**Comment by OneLoneCoder** [comment]
Setting the cursor in Windows is not as simple as it seems - and it looks like you discovered that - however, I consider cursors manipulation to be platform specific - i may address this later this year, but for now it is beyond the scope of PGE.
