### ISSUE TITLE
.PNG Files

### ISSUE THREAD

**Issue by chsjwarrior** [OneLoneCoder/olcPixelGameEngine#74]
I am trying to draw a chess board in olcPixelGameEngine.
I have the pieces images files, saved in .png format.
all works fine but i have problems with the alpha color from the images. The PixelEngine draw all colors and the alpha color too.

**Comment by rumbata2** [comment]
+1, I am using sprites with transparent backgrounds for the pieces but when I draw them, the background seems to automatically turn to white. Are we missing an easy solution here?

**Comment by matt-hayward** [comment]
You need to set the pixel mode when drawing transparent sprites.

```
SetPixelMode(olc::Sprite::ALPHA);
DrawSprite(); // with relevant parameters
SetPixelMode(olc::Sprite::NORMAL);
```

It's important to set the pixel mode back to normal when you are finished drawing transparent sprites as it can otherwise have a negative impact on performance.

**Comment by chsjwarrior** [comment]
It worked, in fact I switched Sprite to Pixel:
SetPixelMode(olc::Pixel::ALPHA);
DrawSprite(); // with relevant parameters
SetPixelMode(olc::Pixel::NORMAL);

thank you matt-hayward

**Comment by matt-hayward** [comment]
@chsjwarrior Good catch, sorry for that. Updated my comment.

**Comment by OneLoneCoder** [comment]
Im tidying the repo, so this gets closed
