### ISSUE TITLE
g++ Procedure Entry Point Error.

### ISSUE THREAD

**Issue by AlC65** [OneLoneCoder/olcPixelGameEngine#78]
If g++ compiles your program  with the Pixel Game Engine v1.24, but you then get the error message "The procedure entry point ...... could not be located in dynamic link library." when you try to run the .exe:
https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html
"If both static and shared libraries are found, the linker gives preference to linking with the shared library unless the -static option is used."
So use:
g++ -std=c++17 source.cpp -static -luser32 -lgdi32 -lopengl32 -lgdiplus -lstdc++fs -lShlwapi

**Comment by ishidex2** [comment]
What platform?

**Comment by AlC65** [comment]
Windows 10.
