### ISSUE TITLE
hello world example does not use full color spectrum

### ISSUE THREAD

**Issue by CullenMoMullen** [OneLoneCoder/olcPixelGameEngine#79]
Sorry for being a pedant.  I really appreciate your engine!  Just curious why you use a modulo 255 rather than 256, when generating your white noise?  Using 255 generates a value [0,254] rather than the desired [0,255], since each color component can have 256 values.

**Comment by OneLoneCoder** [comment]
Yup, this is pedantry at its finest XD. OK, I'll update the code.
