### ISSUE TITLE
virtual destructors and explicit constructors

### ISSUE THREAD

**Issue by jeremiahbreeden** [OneLoneCoder/olcPixelGameEngine#82]
I don't know how open you are to something like this, so if I am overstepping, I do apologize greatly. 

I ran into a small bug when I dynamically allocated a child class instance  of olc::PixelGameEngine and assigned it to a base class pointer and freed it later when the game engine finished and I no longer needed the instance.  It failed to call the destructor in my child class instance

Normally this works, but not for children of olc::PixelGameEngine.  Upon further examination, I found that despite providing virtual functions, the PixelGameEngine  does not provide a virtual destructor.  This causes C++ to not dispatch to the correct destructor when I deleted the base class pointer.  

I would recommend adding an empty virtual destructor:
```C
virtual ~PixelGameEngine() {}
```

to olc::PixelGameEngine

The other thing is just a suggestion.  For constructors using only one parameter (not including copy constructors), it is normal good practice to mark them as explicit.  Otherwise they introduce sometimes unintended implicit conversions.  The Pixel struct has one of these type of constructors that takes a 32bit value in.  Imagine a function:

```C
void test_explicit(olc::Pixel p){
   // Do some stuff with this pixel
}
```

and then someone makes a coding mistake:
```C
test_explicit(some_line_length);  // Oops!  This was supposed to be a pixel, but it compiles fine
```

Again, just a suggestion, but I would recommend adding the "explicit" keyword to that constructor
```C
explicit Pixel(uint32_t p);
```

Then the compiler would catch that coding mistake saying it couldn't convert the int to a Pixel.  The way you would need to call it would be:
```C
test_explicit(  olc::Pixel(some_pixel_value)  );   
```

Which highlights that it should be a Pixel that is being passed.  Of course, if you are using variables of type Pixel, then you would just pass that into test_explicit() as normal with no difference than before.

I tested these in a local copy with the example provided and it compiled and ran well.  If you are interested in either of these changes, I can try and issue a PR instead, but wanted to see if this is something that you are interested in.  The changes are small enough (one line and one word) that they can be added in whenever as well (so doesn't need  a PR if someone just wants to plop them in the next time a change is updated).

**Comment by jeremiahbreeden** [comment]
This is an example program highlighting both things.  If you compile and run this, you will see the destructor is not called and that the test_explicit() function compiles fine when passed an integer

```C
#include <stdio.h>

#define OLC_PGE_APPLICATION
#include "olcPixelGameEngine.h"

void test_explicit(olc::Pixel p){
   // Do some work on the pixel
}

class Example : public olc::PixelGameEngine
	{
	public:
		Example()
		{
			sAppName = "Example";
		}
		~Example(){
			printf("Destructed\r\n");
		}
	public:
		bool OnUserCreate() override
		{
			// Called once at the start, so create things here
			return true;
		}
		bool OnUserUpdate(float fElapsedTime) override
		{
			// called once per frame, draws random coloured pixels
			for (int x = 0; x < ScreenWidth(); x++)
				for (int y = 0; y < ScreenHeight(); y++)
					Draw(x, y, olc::Pixel(rand() % 255, rand() % 255, rand()% 255));
			return true;
		}
	};
	int main()
	{
		test_explicit(23);  // This implicitly converts to a pixel.  is it one?  Who knows

		olc::PixelGameEngine *demo = new Example();
		if (demo->Construct(256, 240, 4, 4))
			demo->Start();

		delete demo;   // The destructor doesn't fire here
		return 0;
	}
```

**Comment by OneLoneCoder** [comment]
Thanks, I'm happy to add a destructor. As for the explicit pixels, I and others do too many tricks with the fact its an integer internally, that I dont want to impede that.

**Comment by jeremiahbreeden** [comment]
@OneLoneCoder Ok Thanks! I understand.  I only brought up the constructors because they are one of the stereo typical "code smells" in C++.  I totally get wanting to preserve backwards compatibility.  Thanks for considering this.  Is your preference for me to close this issue or to wait for the virtual destructor to get added prior to closing?

Thanks again!
