### ISSUE TITLE
Calling olc functions from another class

### ISSUE THREAD

**Issue by wdrDarx** [OneLoneCoder/olcPixelGameEngine#83]
How could I call a PixelGameEngine::FillRect() function from another class like "class sprite(){}"?
How do I get that static reference?

**Comment by OneLoneCoder** [comment]
Ordinarily, if you want objects to draw themselves you would create a DrawYourself(olc::PixelGameEngine* pge) function.

**Comment by UnusefulCoder** [comment]
> How could I call a PixelGameEngine::FillRect() function from another class like "class sprite(){}"?
> How do I get that static reference?

The methods in the class "PixelGameEngine" aren't static. You will need to create a instance of that class to use the methods:
`PixelGameEngine *pge = new PixelGameEngine()`

**Comment by OneLoneCoder** [comment]
I really dont recommend this approach. All sorts of nastiness can happen. Keep one instance of the PGE and pass it around as reference or pointer.

**Comment by UnusefulCoder** [comment]
> [...] Keep one instance of the PGE [...]
The second approach is to use the class `Example` like you said: "keep one" and "pass around", but gives the ability to create new functions without modify the original header (to be used in other projects).
