### ISSUE TITLE
Vector2 thoughts

### ISSUE THREAD

**Issue by remcopeereboom** [OneLoneCoder/olcPixelGameEngine#87]
### Unary Operators

The vector class does not support unary negation. For completeness we could also consider unary addition, even if using that is pretty much always computational overhead in practice.
````cpp
v2d_generic  operator +  () const { return {x, y}; }
v2d_generic  operator -  () const { return {-x, -y}; }
````

### Index Operators

It can be nice to index into the vector.

````cpp
T operator () (int i) const { return (i == 0 ? x : y ); }
T& operator () (int i) { return (i == 0 ? x : y ); }
````

### `mag()`

Right now the magnitude of a vector is casted to type T. This will usually cause a loss of precision, especially for integral types. It could simply return a `double` and then the client can choose what to do with it. This will also ensure that `norm()` returns the correct result for `float` (by waiting for the cast to float until after the reciprocal).

### Inline

Class members are all implicitly `inline` so we can save some horizontal space by getting rid of all the `inline` keywords.

**Comment by ishidex2** [comment]
make a pull request?

**Comment by OneLoneCoder** [comment]
I like these suggestions. OK. I'll put them in for next version.

**Comment by OneLoneCoder** [comment]
That would be 2.08 XD
