### ISSUE TITLE
How to set this up on Xcode

### ISSUE THREAD

**Issue by stonekase** [OneLoneCoder/olcPixelGameEngine#9]
Please is there a way to set this up on Xcode? I am having so many linker errors .

**Comment by Gecero** [comment]
did you added ``#define OLC_PGE_APPLICATION`` before the ``#include "olcPixelGameEngine.h"``?   
if not then add ``#define OLC_PGE_APPLICATION`` over the ``#include "olcPixelGameEngine.h"`` line.

**Comment by OneLoneCoder** [comment]
Hey cheers Gecero :D
