### ISSUE TITLE
Wiki contradicts license

### ISSUE THREAD

**Issue by baccenfutter** [OneLoneCoder/olcPixelGameEngine#90]
There seems to be a very unfortunate typo in the wiki.

The OLC-3 in section `3.` states:
> Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
- https://github.com/OneLoneCoder/olcPixelGameEngine/blob/master/LICENCE.md

However the wiki states:
> [...] You must credit OneLoneCoder in a visible way, [...]
- https://github.com/OneLoneCoder/olcPixelGameEngine/wiki#am-i-allowed-to-use-it

I believe it was meant to read something along the lines of:
> [...] You must redistributed under the OLC-3, [...]

Not?

**Comment by OneLoneCoder** [comment]
No, Clause 3 is to stop people saying "Javidx9 endorses my game". The rest of the lic insists that it is made known to the user that the PixelGameEngine was used.
