### ISSUE TITLE
Pixel constructor perfomance

### ISSUE THREAD

**Issue by jarekpelczar** [OneLoneCoder/olcPixelGameEngine#91]
I modified RGB constructor to look like the following:

`	
        Pixel::Pixel(uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha)

	{ n = red | (green << 8) | (blue <<16) | (alpha <<24); }

`
The difference on olcExampleProgram is around +10FPS (Threadripper 2920X in VMWare), as compiler generates 4 movb store instruction instead of doing calculation on registers. This is also evident on ARM assembly code (4 strb stores vs 1 word store). Compiler is GCC9.

**Comment by OneLoneCoder** [comment]
Thats very interesting! I'll add that in.
