### ISSUE TITLE
Consider adding more control over the game window 

### ISSUE THREAD

**Issue by XenoMustache** [OneLoneCoder/olcPixelGameEngine#95]
Currently the game engine is very locked out when it comes to window control features, unless the user wants to directly edit the header file and force the engine to do exactly what they want. My suggestion is this: add more standard control over the window control that you see in other game engines.

**What am I talking about?**
Currently, there does not appear to be a way to add an icon to the application. While not entirely vital, it would be nice to be able to change this, and add a custom icon to the window, as well as the taskbar.

There is no simple way to enable resizing and maximization control, it would be wonderful to be able to use these options on the game window, as it would make an application feel more complete, as well as user friendly.

On the topic of resolution controls, fullscreen options would also be a welcome addition, as from what I have seen so far there seems to be no support for this at all (I could be wrong, however). Essentially the same principles as the previous suggestion, only to give the imaginary end user more control over the game.

More customization over the title bar would be another welcome feature, perhaps giving the ability to hide the message that come accompanied with the game's name, as well as the fps counter. Perhaps allowing us to add our own things to the title would prove swell as well, such as a score counter for example.

_Normally I wouldn't suggest features like this under the principle that I could simply add them myself in my own codebase, but these features feel like they should be integrated into the primary codebase as to improve ease of use for other users, not just myself._

**Comment by OneLoneCoder** [comment]
Adding an icon is a very platform specific thing - each compiler/platform will have its own way of handling this, and is absolutely nothing to do with the game engine used.

The window is resizeable, just drag the corner. Though I agree, there are no maximise or minimise buttons.

Full screen has always been available, just specify it in the Construct() function. There isnt currently a function for dynamic switching to full screen. I may consider this in the future.

The title bar (unmodified) makes people compliant with the licence by default. If people want to change this, they can. Though I will consider an override.

**Comment by ishidex2** [comment]
@OneLoneCoder in windows its usually stored in resource files of a program, though, its compiled into the executable. On Linux you need .desktop file that defines the icon, which is absolutely not related to engine, and in fact, can be done even now. I have made some programs with winapi and had icon added to it, so I might be able to add ability to add custom icons for windows, if needed.

**Comment by ishidex2** [comment]
With .exe editors you can add icon right now, with source code as it is.

**Comment by Tau5** [comment]
Is it legally possible to change the title on the code to not display the onelonecoder.com message and just add a notice alongside the code and binary about the changes (Obviously, there will be a "Made with OLC PixelEngine onelonecoder.com" at bootup)?

**Comment by OneLoneCoder** [comment]
If you wish to change the titlebar text, then you can, but yes adherence to the licence requires a "made with..." or similar.
