### ISSUE TITLE
MinGW-W64 8.1.0 32-bit version

### ISSUE THREAD

**Issue by MorenoCat** [OneLoneCoder/olcPixelGameEngine#96]
Hello, javidx9 and thanks for your hard work! You really have pedagogical qualities, passion and patience. Now without further ado :D

I have issues compiling the latest version of the engine with MinGW-W64 8.1.0 32-bit version and Codeblocks. I know that the recommendation would be to switch to Visual Studio the latest, but it's not an option to me, so I have to stick with what I have here. In this version of MinGW filesystem file is located here: 
i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\lib\gcc\i686-w64-mingw32\8.1.0\include\c++.
Changing the engine header file to point to the location of the file doesn't solve the issue though, because at the next line we have namespace _gfs = std::experimental::filesystem::v
Compiler complains about this one too: " std::experimental' has not been declared "
Is there any way I can make it compile with the compiler I have without messing too much with the engine?

I find your work very interesting and your engine presents some very nice features packed in a very compact way, that's why I absolutely need to experiment with it.

Cheers and stay healthy!

**Comment by OneLoneCoder** [comment]
Thanks!
The issue here is MinGW is quite fragmented. In the header file itself there are instructions on how to get an up to date MinGW, they are quite simple. I'd recommend trying this first. Also, make sure you are compiling with C++14 or C++17. The PGE is tested on Code::Blocks with MinGW so it does work, but it seems the compiler that ships with code::blocks is quite out of date.

**Comment by OneLoneCoder** [comment]
![2020-04-15_09-31-39](https://user-images.githubusercontent.com/25419386/79316214-f1fcf780-7efb-11ea-9308-577b11c8c9fc.gif)

**Comment by OneLoneCoder** [comment]
You could also looking into the PR if you simply cannot upgrade your compiler, I cant guarantee it will help, and as PGE2 is fluxing at the moment you may need to keep making the change https://github.com/OneLoneCoder/olcPixelGameEngine/pull/80

**Comment by MorenoCat** [comment]
I updated the compiler using MSYS32 tool
Currently I have:
gcc version : 9.3.0
Codeblocks::Blocks version : 17.12
As the compiler didn't understand to define _WIN32 and at preprocessing it kept scrambling everything, I had to set it manually in Codeblocks:
Settings->Compiler->Compiler settings->Defines     _WIN32
I give all these details so that anybody who encounters the same problem and happens to read this post to know what I've done and how I made it work.
With that little tweak I made it compile and see those nice pixels making noise on the display.
Now it's time to start the exploration. :)
Thank's again and keep up the good work!

**Comment by Cesar-Raitz** [comment]
I could not compile with the **i686-8.1.0-posix-dwarf-rt_v6-rev0** distro either (I'm using VS Code). Even by using the **-std=c++17** flag, g++ complained about **std::filesystem::path** not having the **!=** operator. I had to download the 64 bit compiler from https://nuwen.net/mingw.html. I guess 32 bit Windowses are off the play for v2.0?

**Comment by OneLoneCoder** [comment]
PGE has been successfully compiled in 32 and 64 bit modes, for both linux and windows, using a variety of mainstream compilers - from what ive observed via the feedback, is there are some linux distros that dont keep their "packaged" compilers up to date (by some margin). In those cases there is little I can do, and need to rely on the user's competence with their environments.
